### PR TITLE
Avoid downloading when TOPHUB_LOCATION is NONE

### PR DESCRIPTION
**Pull request by lixiaoquan**

### CODE REVIEW

**Comment by comaniac** [comment]
Could you provide the background of making this change?

**Comment by lixiaoquan** [comment]
> Could you provide the background of making this change?

TOPHUB_LOCATION is introduced by #4015 to disable downloading from tophub, but behavior of this environment variable is broken.

**Comment by comaniac** [comment]
I see. The behavior was removed by #4671. Will take a closer look tomorrow morning.

Also cc @zxy844288792

**Comment by lixiaoquan** [comment]
This PR won't affect what #4671 want to achieve, if TOPHUB_LOCATION is not set(which is default behavior), config will be downloaded if not exsit.

**Comment by zxy844288792** [comment]
> This PR won't affect what #4671 want to achieve, if TOPHUB_LOCATION is not set(which is default behavior), config will be downloaded if not exsit.

I agree with you, did not realize the existence of AUTOTVM_TOPHUB_NONE_LOC.

**Pull request merged**
