### PR TITLE
[Build] Explicitly link to cublasLt if it exists

### PR DESCRIPTION
**Pull request by soiferj**
Currently, the Windows build fails due to the linker not being able to find cublasLt functions. This change explicitly links to cublasLt.

@Laurawly @masahi @Hzfengsy would you be able to take a look?

### CODE REVIEW

**Comment by masahi** [comment]
@soiferj the CI is at CUDA 10.0, so it doesn't have cublaslt lib.

**Comment by soiferj** [comment]
Got it. In that case, I’ll update the logic to only link if it found the library.


________________________________

**Comment by soiferj** [comment]
@masahi fixed. Would you mind taking another look?

**Comment by masahi** [comment]
thanks @soiferj

**Pull request merged**
