### PR TITLE
[CI] Install DNNL (OneDNN) to CI Environment

### PR DESCRIPTION
**Pull request by comaniac**
The current BYOC flow uses DNNL as an example backend to demonstrate and test its functionality, but all related tests are currently skipped in CI due to the lack of DNNL in the environment. In this PR, we add scripts to deploy pre-built DNNL to the docker image so that the unit tests in #5919 for example can be effective.

I've built a docker image locally and passed unit tests of #5919 with it.

cc @zhiics @tqchen

### CODE REVIEW

**Comment by tqchen** [comment]
Please confirm if the dnnl works with AMD cpu, as we also have AMD cpus in the CI.

**Comment by comaniac** [comment]
OK will verify it on EC2 A1 instance and get back here.

**Comment by comaniac** [comment]
Verified that this docker image with DNNL works for AMD CPU (EC2 m5a.4xlarge instance).

**Comment by tqchen** [comment]
OK, this is merged. the binary need to be manually updated,  will report back when it is ready,

**Comment by comaniac** [comment]
HI @tqchen have you got a chance to update docker hub? Thanks.

**Comment by tqchen** [comment]
Update, I tried to update. There was some problems wrt to the ci-cpu(not related to this PR) that needs to be fixed http://ci.tvm.ai:8080/job/temp-ci-docker-staging/job/ci-stage/39/execution/node/324/log/ before we can update the image

**Comment by comaniac** [comment]
Got it. Thanks for the update!

**Pull request merged**
