### PR TITLE
[Relay/TOPI/TF][Op] Add support for randomuniform Op in TVM

### PR DESCRIPTION
**Pull request by deepakbabel**
Thanks for contributing to TVM!   Please refer to guideline https://docs.tvm.ai/contribute/ for useful information and tips. After the pull request is submitted, please request code reviews from [Reviewers](https://github.com/apache/incubator-tvm/blob/master/CONTRIBUTORS.md#reviewers) by @ them in the pull request thread.

### CODE REVIEW

**Comment by MarisaKirisame** [comment]
this has unnecessary effect (nondeterminism). 
can you make it input a random seed and output a random seed?

**Comment by MarisaKirisame** [comment]
@jroesch @tqchen Having effect in the TVM ir will make optimization on that level harder (because now it has to do effect analysis), and effect do not play nice with Relay's graph representation. I personally think that all TVM operator should be referential transparent, and the effect should happen at the relay level.

**Comment by tqchen** [comment]
I think it worth start an RFC discussion thread about how are we going to handle PRNGs in general. In particular, I agree that in the relay API, perhaps it is easier(for optimization) to make the RPNG takes in an RNG object and outputs an RNG object to preserve the ordering. 

At the low-level though, I am not sure what is the exact approach we would like to take. At some timepoint we will need to go back to the stateful land where we keep a PRNG state somewhere (in CPU or GPU)

**Comment by deepakbabel** [comment]
@yongwww , Adding you also to the reviewer list

**Comment by deepakbabel** [comment]
> this has unnecessary effect (nondeterminism).
> can you make it input a random seed and output a random seed?
Thank you for your inputs. The original intent here was if the user would provide an input seed(as per the user choice) and desired shape of RNG object and the function would generate the RNG object based on the same. If the user uses the same seed(seed value != 0) again in the same session, he would get the same RNG object. Only for seed value == 0, non-determinism kicks in and the RNG object would be different for each run in a given session.
Does it make sense? Let me know if I understood you correctly and the response is on the same lines.

**Comment by MarisaKirisame** [comment]
@tqchen I agree that at some level we should provide a stateful api. I think it will be best provided in relay. For example, there will be a global mutable reference holding a seed, and there are relay wrapper that call the pure tvm operator with the old seed, and store the new seed.
Or one could think about a relay pass that transform stuff into PRNG passing style.

@deepakbabel the function should at least output the new seed then.

**Comment by maheshambule** [comment]
@MarisaKirisame, could you please elaborate more on outputting the new seed?  Does it mean that in case if seed is not provided Relay should generate (and not the operator to keep it pure) a new seed,  pass it to the operator and then store it in a global mutable reference at Relay level. And in case if seed is provided just pass it to the operator.

**Comment by MarisaKirisame** [comment]
I am proposing the following design:
the tvm operator randomuniform take a seed, and return a random uniform tensor paired with the new seed.
relay has a global reference holding a seed.
there are relay helper function that, read the seed, call randomuniform, write the new seed to the reference, and returning the tensor.
this way, the tvm level can be kept pure, which is beneficial for optimization, while the relay level provide effectful api that is easy to use.

**Comment by maheshambule** [comment]
Thanks @MarisaKirisame. I understand that We want to keep TVM operator pure and Relay can have side effects. But I am not able to figure out Why do we want the operator to return the new seed? And how that new seed will get generated?

**Comment by MarisaKirisame** [comment]
Because if there is only one seed, every random uniform call will return the same result for the same tensor size.
Internally, the random computation proceed already by using a random number genrator and advancing the seed. This is the implementation detail of the PRNG.

**Comment by deepakbabel** [comment]
Hi @MarisaKirisame 
I understand now that in the new design proposed by you, we want to enforce unique random sequences every-time even if the input seed provided by user is same between multiple session executions. We are internally using C++11 std::mt19937 generator for PRNG generation. There are no such API available in this generator which returns a new random seed value along with the output RNG object. Please see "src/runtime/contrib/random/mt_random_engine.cc" for more details.
In such case how do you propose getting the new random seed. Also this piece of tvm code for PRNG generation(mt_random_engine.cc, random.cc) was pre-existing in contrib layer, we have just provided support in relay and topi layers so that it can be called by both these layers.

**Comment by deepakbabel** [comment]
tf_random
Even if we use tf, we get the same sequence even if we use global and operation seeds in conjunction across multiple session calls

**Comment by tqchen** [comment]
To chime in a bit here. I think the main thing that need to be discussed is not the implementation, but how can PRNG being represented in the high-level relay graph. 

Inherently, the low level program need to have some of the opaque global states in certain execution mode(e.g. IO, PRNG or cudnn handle). It does not, however, prevent us from adopting a functional style program at the high-level. as these functional style program can still be lowered into low-level program that has side-effect(via a global random number generator).

```python
data1, rng = uniform(rng, shape)
data2, rng = uniform(rng, shape)
```

For example, the program above can be lowered by ignoring `rng` as an empty object, but makes use of the data flow dep to preserve ordering of the random numbers(where before they do not have dependencies.

We do however, would like to discussion a few alternatives, and how to best represent such program in relay overall. Functional style program representation is easier to transform, distribute, but also brings interesting challenge about how to construct them initially from program that may not have a functional form. Let us open an RFC to discuss that

**Comment by JoeyTPChou** [comment]
Hi, just wanna check, is there still a plan to merge this PR?

**Pull request closed without merging**
