### PR TITLE
[PYTORCH]Minor bug fixes

### PR DESCRIPTION
**Pull request by siju-samuel**
Bugfixes
- arange -> start/stop/end may be already expr, so no need to create typedconst that time.
- slice -> begin_dim may be an expr, so need to evaluate and find int and pass the value.
- numtotensor -> input may be already an expr, no need to convert.
- view -> if any value of new size is expr, need to evaluate and find the shape values.

This can be simulated by running bert models.

### CODE REVIEW

**Comment by masahi** [comment]
Can you add tests? Otherwise it's hard to tell what the problems are. Adding BERT to tests sounds interesting.

**Comment by siju-samuel** [comment]
BERT has dependancy with pip package `pytorch_pretrained_bert`. i will add some bert testcases later. May be we can add as another tutorial also.

**Comment by masahi** [comment]
You can add BERT tests to the repo and only execute them if import succeeds. They won't be run on CI but we can test them locally. Since BERT seems popular, it would be nice to have an example of how to load them with our PyTorch frontend.

@siju-samuel Do you want to do it? Otherwise I can merge this as it is.

**Comment by tqchen** [comment]
One middle ground would be manually construct some snippet that relates to bert but not directly use th bert model itself

**Comment by masahi** [comment]
yes this is also a good option if the model is not too complicated. It is up to @siju-samuel. See our lstm tests https://github.com/apache/incubator-tvm/blob/master/tests/python/frontend/pytorch/lstm_test.py

**Comment by masahi** [comment]
Thanks @siju-samuel

**Pull request merged**
