### PR TITLE
Update legacy places from nnvm to relay.

### PR DESCRIPTION
**Pull request by tqchen**
Related to https://github.com/apache/incubator-tvm/issues/4496

NOTE: I wasn't able to test rust code mainly due to historical problem of rust build not being stablized. I did manage to update the model creation script though.

Would be great to get some further help to get rust back to the CI. cc @nhynes @jroesch

### CODE REVIEW

**Comment by nhynes** [comment]
> Would be great to get some further help to get rust back to the CI

Sure. Any chance #2885 will be merged in my lifetime? That one contains some fixes to the Rust runtime that I've been batching up.

**Comment by tqchen** [comment]
@nhynes of course, sorry that I lost track, please directly ping again next time if the issue requires action :)

**Comment by icemelon9** [comment]
Should we also remove the `test_python_legacy` from CI?

**Comment by tqchen** [comment]
@icemelon9 i plan to do that in followup PR. we also need to remove the reference to nnvm in the autotvm python package before removing the nnvm source. let me know if you are interested in help on some of the steps

**Pull request merged**
