### PR TITLE
ROCm: use GcnArch for mcpu and ApiVersion to select code object version

### PR DESCRIPTION
**Pull request by t-vi**
This is a ROCm followup for #6347 bringing the code that was moved from src/target/llvm/codegen_amdgpu.cc to src/target/target_kind.cc closer to the old mechanism for compute arch autodetection.
@junrushao1994 @masahi

### CODE REVIEW

**Comment by junrushao1994** [comment]
I see. So there are actually two version, one ApiVersion, which is used to decide whether to add "-code-object-v3" into mattr; Another is GcnArch, which is used to decode "mcpu". Thank you for the clarification!

**Review by junrushao1994 — APPROVED** [review]
LGTM!

**Review by tqchen — APPROVED** [review]

**Comment by t-vi** [comment]
@junrushao1994 Yeah, and I'll admit that I wouldn't have spotted it without trying to run it on the hardware that is particular about it...
I actually hope that we might be able to drop the code-object thing in due time, but so 3.5 (which changed this) was released in June and I'm not sure how long we would need to give people to upgrade ROCm.

**Review by masahi — APPROVED** [review]
Confirmed locally that it works. Thanks.

**Comment by masahi** [comment]
Thanks @t-vi @junrushao1994 @tqchen

**Pull request merged**
