### PR TITLE
Add beagleboard ai, thunderx and stm32mp1 to the arm_cpu target.

### PR DESCRIPTION
**Pull request by tom-gall**
This adds three new models to the arm_cpu target. Two 32 bit devices, the beagle board-X15 and the STM32MP1, and a 64 bit device the ThunderX server.

Signed-off-by: Tom Gall <tom.gall@linaro.org>

### CODE REVIEW

**Review by leandron — COMMENTED** [review]
CI flagged this because of a new linting tool that was introduced. To fix that, the simplest way I use is below, supposing this change is the last on your repo:

```
# assuming you are in the "incubator-tvm" directory, this will update your files accordingly
./tests/lint/git-black.sh -i HEAD~1
```

**Comment by leandron** [comment]
LGTM

**Review by junrushao1994 — APPROVED** [review]
LGTM. BTW we may consider transition to target tags some day.

**Review by zhiics — APPROVED** [review]

**Comment by zhiics** [comment]
Thanks @tom-gall @leandron @junrushao1994

**Pull request merged**
