### PR TITLE
[Relay][Frontend][Tensorflow] Fix GatherV2, Add StopGradient

### PR DESCRIPTION
**Pull request by trevor-m**
These changes are needed to parse a BERT TF model into relay.

1. GatherV2
TensorFlow recently [added `batch_dims` as an attribute of the GatherV2 op](https://github.com/tensorflow/tensorflow/commit/4d56e9709f1864699be7241a3d1938816d9f31c5#diff-0a1b05e2252bef657373e11f17bfa5d3) to support batched gather. This would cause the parser the fail since it didn't expect that attribute. I added a check to make sure the attribute doesn't change the behavior of the op if it happens to exist and also added it to the ignore list. We can support parsing of batched gather at a later date.

2. StopGradient
This is a training op meant to stop gradient flow over certain edges in the graph. It has no purpose in inference so it can be safely mapped to identity.

### CODE REVIEW

**Comment by kevinthesun** [comment]
@trevor-m Thank you for adding this. Can you take a look at the CI failure.

**Comment by trevor-m** [comment]
> @trevor-m Thank you for adding this. Can you take a look at the CI failure?

Thanks @kevinthesun, the link http://ci.tvm.ai:8080/job/tvm/job/PR-4238/1/display/redirect isn't working for me.

**Comment by yzhliu** [comment]
please kick ci later.

**Comment by MarisaKirisame** [comment]
I object mapping it to identity directly. Can it be replaced with an operator that map to identity, and has grad of 0?

**Comment by trevor-m** [comment]
> I object mapping it to identity directly, because we have an ad algorithm. Can it be replaced with an operator that map to identity, and has grad of 0?

That makes sense to me. How do you see this being implemented? Do you mean creating a new op in relay or is there a way to do it just in the parser?

Looks like nnvm had an op `block_grad` which is equivalent to StopGradients.

**Comment by MarisaKirisame** [comment]
You have to create an op in relay.
Then, it will have a grad function, which will return [zeros_like(orig.args[0])].
It wont be a big change (probably ~30 lines, most of which will be copied), and it will help you learn a bit about the stack.
I can do it if you found it too difficult though.

**Comment by trevor-m** [comment]
That sounds good, thanks for the description!

I’ll update this PR with the change shortly.

**Pull request merged**
