### PR TITLE
[RELAY] Partition graph codestyle fixes

### PR DESCRIPTION
**Pull request by manupa-arm**
Follow-up PR for codestyle changes for PR #5143
cc : @masahi @zhiics @comaniac

### CODE REVIEW

**Comment by masahi** [comment]
For emacs and clangd users, you can simply do `M-x indent-region` and clangd would indent and format using clang-format + our .clang-format config automatically.

**Comment by manupa-arm** [comment]
It would have been nicer to somehow capture this in lint ? Probably using clang-format itself. Are you aware of any prior discussion/PR on this?

**Comment by zhiics** [comment]
Maybe we can set clang tidy up.

**Comment by masahi** [comment]
I think it is too late to enforce the style clang-format would choose using lint. We have too many existing code that violates this style (.clang-format file itself was introduced much later in the development).

**Comment by zhiics** [comment]
exactly. we will need a lot of fixes.

**Comment by manupa-arm** [comment]
How about giving out warnings, initially?

**Comment by zhiics** [comment]
You can probably open a thread in the discussion forum.

**Comment by masahi** [comment]
I actually prefer doing the massive style change once and for all, and enforce this style during lint moving forward.

**Comment by comaniac** [comment]
I agree with @masahi. We did that for the doc warning weeks ago and added a checker to CI. We should do that for style too, although the workload of correcting C++ style in an entire code base is definitely in another scale.

**Comment by masahi** [comment]
Thanks @manupa-arm @mbaret

**Pull request merged**
