### PR TITLE
[VTA] Bug fix for padded load with large inputs

### PR DESCRIPTION
**Pull request by liangfu**
This PR brings the support for padded load with large inputs (greater than a single burst length).

@vegaluisjose @tmoreau89 Please review.

### CODE REVIEW

**Comment by liangfu** [comment]
@vegaluisjose Yes, current Chisel implement passes all the unit-tests.

@tmoreau89 I did not test this with HLS version yet. If you want, I think I can test this with PYNQ hardware next week.

On the other hand, I think some recent changes (either in the runtime or the compiler) has made this broken. I mean even without this PR, unit test with `fsim` could even fail in some cases (not always). I can reproduce the failure case by fixing random seed. All my successful tests are based on eariler version of runtime & compiler. This PR only focus on the hardware improvements.

**Comment by tmoreau89** [comment]
Thank you @liangfu; if you could test the unit test on Pynq that would be excellent; one known issue is that the padded load test fails on Pynq (but not in fsim); so I was wondering if some changes to the test would fix it. If it still fails, it's not worse off than it is now. That will require some digging into, which I can do when I have bandwidth. For now a simple yes/no report on pass status would be sufficiently good.

**Comment by liangfu** [comment]
> one known issue is that the padded load test fails on Pynq (but not in fsim); so I was wondering if some changes to the test would fix it.

This PR is intended to bring the fix, and it does fix the issue.

For the failure case that I referred earlier happens in recent changes in either runtime or compiler, not in the hardware implementation. I can successfully evaluate the padded load test with this PR + runtime and compiler in commit [734df8d](https://github.com/apache/incubator-tvm/commit/734df8d59b8a9c58cfd87eaca49e635c2ef39e81).

**Comment by tmoreau89** [comment]
Thanks. @vegaluisjose pending your approval I'll merge the changes.

**Comment by vegaluisjose** [comment]
LGTM

**Pull request merged**
