### PR TITLE
[Relay][VM] Add ReshapeTensor instruction in the VM to replace the reshape op

### PR DESCRIPTION
**Pull request by icemelon9**
@jroesch @zhiics @mbrookhart Could you help review?

### CODE REVIEW

**Comment by zhiics** [comment]
Please check the error. It cannot be executed on GPU.

**Comment by mbrookhart** [comment]
The GPU error seems to come from the check I added to fail early on GPU with dynamic models. I believe dynamic shapes wont work on cuda until we get heterogenous execution working for shape funcs, per our discussion in https://discuss.tvm.ai/t/issue-with-vm-execution-when-testing-gpu-immediately-after-cpu/7010/7

@zhiics, any update on that work? Or should we limit this test to CPU?

**Comment by zhiics** [comment]
@mbrookhart Yeah, I meant there is gpu context in the test. That's why the ci fails. We can probably just disable check_result for this test ATM. Heterogeneous execution needs this PR.

**Comment by zhiics** [comment]
Thanks @icemelon9 @mbrookhart

**Comment by MarisaKirisame** [comment]
@icemelon9 is_reshape_only is incorrect. If a function return a constant it will wrap a reshape on it. Please fix it in a principle way (e.g. not by checking that the whole function has at least one reshape, as this will not work on reshape of constant).

**Pull request merged**
