### PR TITLE
[TOPI] Fix missing import in bifrost schedule

### PR DESCRIPTION
**Pull request by roastduck**
#6473 

Added the missing import.

I did not any new tests since I cannot fix pytest.

@tqchen please have a look.

### CODE REVIEW

**Comment by roastduck** [comment]
Why does the CI complaint about something I did not modify?

**Comment by tqchen** [comment]
@roastduck you can try to apply `tests/script/git-black.sh -i upstream/master`

**Comment by roastduck** [comment]
Rebased to the latest commit, hoping it will pass the CI.

**Review by tqchen — APPROVED** [review]

**Comment by tqchen** [comment]
Thanks @roastduck !

**Pull request merged**
