### PR TITLE
[Doc] Fix doc-string in `compile_engine.py`

### PR DESCRIPTION
**Pull request by hgt312**
Thanks for contributing to TVM!   Please refer to guideline https://docs.tvm.ai/contribute/ for useful information and tips. After the pull request is submitted, please request code reviews from [Reviewers](https://github.com/apache/incubator-tvm/blob/master/CONTRIBUTORS.md#reviewers) by @ them in the pull request thread.

### CODE REVIEW

**Comment by hgt312** [comment]
@junrushao1994 Thanks for reviewing.

**Comment by junrushao1994** [comment]
https://docs.tvm.ai/api/python/relay/backend.html#tvm.relay.backend.compile_engine.CachedFunc

Is this what you are looking for?

**Comment by hgt312** [comment]
`cached_func` is a lowered function, however `JIT` return a packed function.

**Comment by tqchen** [comment]
Thanks @hgt312 @junrushao1994 !

**Pull request merged**
