### PR TITLE
[PYTHON][FFI] Cythonize NDArray.copyto

### PR DESCRIPTION
**Pull request by tqchen**
Improve the efficiency of NDArray.copyto by cythonize it.

### CODE REVIEW

**Comment by tqchen** [comment]
cc @junrushao1994

**Comment by junrushao1994** [comment]
Is there any use cases that this is performance critical?

**Comment by tqchen** [comment]
don't know, it was a short fix that is simple enough that I feel worth the change, always good to make the code a bit faster :)

**Comment by junrushao1994** [comment]
It looks good. Btw in mnm, we treat all dtypes/ctx as strings for convenience. I think packed function has been able to deal with string dtypes, and some time it is worthwhile to do it to ctx as well

**Comment by tqchen** [comment]
cc @yzhliu

**Pull request merged**
