### PR TITLE
[Bugfix][Serialization] Fix runtime::String backward compatibility in JSON

### PR DESCRIPTION
**Pull request by junrushao1994**
@antinucleon sent me a JSON file which cannot be loaded in current HEAD on master. After bisecting around, I found that there are some missing parts (or just typos I think) in json_compact.py...

Also CC: @tqchen @jwfromm @ANSHUMAN87 if you guys are interested

### CODE REVIEW

**Comment by ANSHUMAN87** [comment]
Thanks @junrushao1994 !
As i remember, I had handled version upgrade for "GlobalVar" in PR (#5547).
So maybe we need to discuss how it got bypassed?
I saw the changes in jason_compact.py, just wonder why below code did not work:
`"relay.GlobalVar": [_rename("GlobalVar"), _update_from_std_str("name_hint")],`

I understand the issue is because of the key name difference "relay.Global" vs "Global".
Please correct me if my understanding is wrong.

**Comment by tqchen** [comment]
Thansk @junrushao1994

**Comment by junrushao1994** [comment]
@ANSHUMAN87 yeah you are right. This is all about the type name.

It is a bit tricky, because the JSON string was generated after 0.6.0 where type name is changed from relay.GlobalVar to GlobalVar, but before your PR #5547. This means that we still need to cover the case for GlobalVar :-)

**Comment by ANSHUMAN87** [comment]
@junrushao1994 : Thanks a lot for clarifying! :+1:

**Pull request merged**
