### PR TITLE
fix a bug in convertSSA.

### PR DESCRIPTION
**Pull request by Presburger**
Thanks for contributing to TVM!   Please refer to guideline https://tvm.apache.org/docs/contribute/ for useful information and tips. After the pull request is submitted, please request code reviews from [Reviewers](https://github.com/apache/incubator-tvm/blob/master/CONTRIBUTORS.md#reviewers) by @ them in the pull request thread.
@merrymercy

### CODE REVIEW

**Review by leandron — COMMENTED** [review]
Hi @Presburger, thanks for the PR.

Would you mind editing the description of this PR, describing why this fix is needed, or where do you see the bug you're fixing? Also, it would be interesting to add a test case, to make sure this is checked and don't regress in future.

**Comment by Presburger** [comment]
OK, @leandron 
I find a IR look like this before Loop Partition.
```cc
for(i1: int32, 0, 36){
    attr [IterVar(x.inner, (nullptr), "DataPar", "")]{
    for (x.inner, 0, 9) {
        if(likely(i1<18))
        .....
        else
        .....
}
}
} 
```
Loop Partition will transform this IR to
```cc
for(i1: int32, 0, 18){
    attr [IterVar(x.inner, (nullptr), "DataPar", "")]{
    for (x.inner, 0, 9) {
        .....
}
}
}
for(i1: int32, 18, 36){
    attr [IterVar(x.inner, (nullptr), "DataPar", "")]{
    for (x.inner, 0, 9) {
        .....
}
}
}
```
then IR pass to ConvertSSA, when visited secnd for loop 's x.inner, tvm may crash.
because try to call vector::back when the vector container is empty.

**Comment by tqchen** [comment]
Thanks @Presburger ! It would be awesome to add a testcase to cover the problem

**Review by tqchen — APPROVED** [review]

**Comment by tqchen** [comment]
Merging for now as it is a quick case, but a testcase would still be appreciated :) Thanks @leandron @Presburger

**Pull request merged**
