### PR TITLE
[CI] Update MxNet to 1.6.0 with MKL

### PR DESCRIPTION
**Pull request by icemelon9**
Thanks for contributing to TVM!   Please refer to guideline https://tvm.apache.org/docs/contribute/ for useful information and tips. After the pull request is submitted, please request code reviews from [Reviewers](https://github.com/apache/incubator-tvm/blob/master/CONTRIBUTORS.md#reviewers) by @ them in the pull request thread.

cc @eric-haibin-lin @shoubhik @anijain2305

### CODE REVIEW

**Comment by shoubhik** [comment]
yes, when i get time, i'll start adding test cases for quantized mkl.

**Comment by tqchen** [comment]
I will reply to do once the CI image is updated, should be in this week

**Comment by tqchen** [comment]
Just to confirm again, does the mxnet-mkl works on machines with AMD cpu?

**Comment by shoubhik** [comment]
At this time MKL is only compatible with intel CPUs.

**Comment by tqchen** [comment]
Given that we also have machines with AMD CPUs on the CI fleet, and in the future introduce other kinds of CPUs.

It would be great it we can work around the dependency to test the QNN implementations, possibly by using a floating pt reference or slower verison

**Comment by icemelon9** [comment]
So in that case, should we use mxnet==1.6.0 instead of mxnet-mkl?

**Comment by shoubhik** [comment]
Can't we have another step in CI that executes Mxnet Qnn models on intel CPUs only?

**Comment by tqchen** [comment]
That will further complicates the CI itself. It would be great if we can explore other ways to validate and stick with the default mxnet

**Pull request merged**
