### PR TITLE
[uTVM] Enable Testing Standalone uTVM Runtime in CI

### PR DESCRIPTION
**Pull request by liangfu**
Testing standalone uTVM runtime was previously disabled due to 
```c
// Use system(..), `gcc -shared -fPIC`, thus restrict the test to OS X for now.	
#if defined(__APPLE__) && defined(__MACH__)
```
, this PR enables testing the code in CI.

@ajtulloch @weberlo Please review.

### CODE REVIEW

**Comment by Dayananda-V** [comment]
@liangfu 

Still test is not able to run with "Segmentation fault (core dumped)" this error.

**Comment by tqchen** [comment]
@liangfu please update the thread

**Comment by tqchen** [comment]
ping @liangfu

**Comment by liangfu** [comment]
let me close this for now, i will reopen this once CRT is ready to replace current uTVM standalone runtime.

**Pull request closed without merging**
