### PR TITLE
[VTA] improved virtual memory mapping

### PR DESCRIPTION
**Pull request by liangfu**
This PR improves virtual memory mapping in VTA drivers. The feature could be helpful in debugging data inputs and outputs in VTA hardware.

### CODE REVIEW

**Comment by liangfu** [comment]
@tmoreau89 Please review.

**Comment by liangfu** [comment]
Thanks for the review comments. Actually, I have noticed your suggestion in my last PR, and I had a PR #4407 on improving the CI test, but the test was failed.  Shall we solve the issue in that PR?

**Comment by tmoreau89** [comment]
@liangfu thank you, we can solve that issue in the PR #4407

**Comment by tmoreau89** [comment]
The PR has now been merged.

**Pull request merged**
