### PR TITLE
Add Quantize/Dequantize Partitioning

### PR DESCRIPTION
**Pull request by weberlo**
Implements step 1 of the [Improvements to Automatic Quantization for Bare-Metal](https://discuss.tvm.ai/t/rfc-improvements-to-automatic-quantization-for-bare-metal/7108) RFC.

The code still needs more thorough documentation, and I'm gonna wait to bake the visitors into C++ until we get some design feedback (either here or on the RFC).

### CODE REVIEW

**Comment by weberlo** [comment]
CC @ZihengJiang

**Comment by tqchen** [comment]
@weberlo please rebase to resolve the conflict. @ZihengJiang please help manage this PR

**Comment by weberlo** [comment]
@ZihengJiang I've rebased and converted the datatype collector pass into C++, but I won't be prioritizing C++ conversion for the other visitors for the next few weeks.  To prevent bit rot, I think we should work towards merging the PR in its current state.

**Comment by ZihengJiang** [comment]
@weberlo Will this affect the original pipeline when the config `partition_conversions` is `disabled`?

**Comment by tmoreau89** [comment]
Nice work @weberlo, do can we add a `partition_conversions=disabled` unit test as well?

**Comment by weberlo** [comment]
> @weberlo Will this affect the original pipeline when the config `partition_conversions` is `disabled`?

@ZihengJiang It won't affect the original pipeline, since we just return the `mod` [here](https://github.com/apache/incubator-tvm/pull/5940/files#diff-0ca944afca91e5a6d46981a4ac9e3dd6R378) when `partition_conversions` is `disabled`.

> Nice work @weberlo, do can we add a partition_conversions=disabled unit test as well?

It's implicitly tested in [this helper function](https://github.com/apache/incubator-tvm/pull/5940/files#diff-c82103045cf6ee84456fa38e019e074fR143-R146).  I explicitly set it to `disabled` to make it clearer in the most recent commit.

**Comment by ZihengJiang** [comment]
@weberlo I believe we would like a general approach to achieve the partitioning in the future, but I am fine with the PR in the current stage. I will approve it after it pass the tests.

**Comment by weberlo** [comment]
> @weberlo I believe we would like a general approach to achieve the partitioning in the future, but I am fine with the PR in the current stage. I will approve it after it pass the tests.

I agree the current implementation is suboptimal, and it would be much better to integrate it more closely with the quantization pass itself.  I went with the approach in this PR, because you're in the process of making significant changes to quantization, and this approach should be robust to those changes.  We should certainly revisit this feature once your changes land though.

**Comment by weberlo** [comment]
@tmoreau89 @ZihengJiang CI's finally passing

**Comment by ZihengJiang** [comment]
Merged now! Thanks Logan!

**Pull request merged**
