### PR TITLE
Add include path to Rust build script

### PR DESCRIPTION
**Pull request by gussmith23**
@jroesch 

I'm not sure what we want to do here. I needed to add this path to make the build script work on my system -- perhaps there's something I should do on my side, though?

### CODE REVIEW

**Comment by tkonolige** [comment]
Could you post the error message you get when building?

**Comment by gussmith23** [comment]
```
error: failed to run custom build command for `tvm-sys v0.1.0 (https://github.com/apache/incubator-tvm?branch=main#4c4888bc)`

Caused by:
  process didn't exit successfully: `/home/gus/glenside-evaluation/target/debug/build/tvm-sys-6e86f41bfc277513/build-script-build` (exit code: 1)
  --- stdout
  cargo:rerun-if-env-changed=TVM_HOME
  cargo:rustc-link-lib=dylib=tvm
  cargo:rustc-link-search=/home/gus/tvm/build

  --- stderr
  /home/gus/tvm/3rdparty/dlpack/include/dlpack/dlpack.h:30:10: fatal error: 'stddef.h' file not found
  /home/gus/tvm/3rdparty/dlpack/include/dlpack/dlpack.h:30:10: fatal error: 'stddef.h' file not found, err: true
  Error: failed to generate bindings
```

Yeah, I agree that it doesn't seem to make sense. I'm having a hell of a time resolving this on one of our machines, and I have to assume it's because of how the machine is configured. We have stddef.h (multiple, in fact) but I have no idea which toolchain rust is trying to use here, so I don't know which one it's failing to find.

It seems to be happening in bindgen, and there's a running thread about issues like this: https://github.com/rust-lang/rust-bindgen/issues/1226. It seems like it's not actually an issue on their side, but it's common when using bindgen.

**Comment by tkonolige** [comment]
Have you tried specifying `LLVM_CONFIG_PATH`?

**Comment by gussmith23** [comment]
Yes, it's set! I think I was getting a different error before I realized I needed to set that.

**Comment by tqchen** [comment]
Closing, glad that the problem is resolved

**Comment by gussmith23** [comment]
Oops, this problem isn't resolved! Sorry, didn't mean to imply that. I had already set `LLVM_CONFIG_PATH` before getting this error.

**Comment by tqchen** [comment]
In this case it is indeed versy strange that stddef is not part of your include path, how about you add it to your CPLUS_INCLUDE_PATH and C_INCLUDE_PATH env variable in your system?

**Comment by gussmith23** [comment]
I have, to seemingly no effect. I'll bug our sysadmin about this. It must
be on my side.

**Pull request closed without merging**
