### PR TITLE
[Relay] Empty Tuple should be considered as variable

### PR DESCRIPTION
**Pull request by ANSHUMAN87**
@tqchen , @zhiics, @MarisaKirisame

### CODE REVIEW

**Comment by MarisaKirisame** [comment]
Is there any reason that it shouldnt be considered as a constant?

**Comment by ANSHUMAN87** [comment]
@MarisaKirisame , @zhiics : Thanks for reviewing the changes. I am sorry i did not add test case this time cause i thought the test case wont be a valid scenario to represent to a user.

I found this problem while reviewing code for another issue.
To explain the background of it. Please consider below points.
1:> Tuple as mostly adapted datatype does not allow any of the member to get modified once created(position and pointers), so provided that Empty Tuple is a constant.
2:> But in TVM context, the Tuples allows its member to get modified, even after creation, so provided that Empty Tuple is a variable(Get modified afterwards).

Please correct me if i am wrong at any point.

I just handled for the fold_constant, as it was part of my analysis currently.

But in my personal opinion, all Tuple Nodes should be Immutable.
If you think TVM should implement Tuple as Immutable, i will close this PR(there is no point of checking for Empty Tuple as it becomes constant, once created)

Please provide your valuable opinions. Thanks!

**Comment by MarisaKirisame** [comment]
@ANSHUMAN87 it is impossible to modify a tuple.

**Comment by ANSHUMAN87** [comment]
> @ANSHUMAN87 it is impossible to modify a tuple.

@MarisaKirisame, @zhiics  : Extremely sorry for late reply. I believe there was some temp changes in my workspace, which led to such conclusion. Closing the PR. Thanks for your help!

**Pull request closed without merging**
