### PR TITLE
[Autotvm] Use VM compile to extract autotvm tasks

### PR DESCRIPTION
**Pull request by icemelon9**
Current autotvm relay integration doesn't support extract autotvm tasks from a module.

### CODE REVIEW

**Comment by icemelon9** [comment]
@tmoreau89 @merrymercy Could you help review the pr?

**Comment by comaniac** [comment]
Did you measure the time to extract tasks using Relay VM?
The recent PR #4138 has optimizes the task extraction time, so I am cauious if it would be faster or slower when using Relay VM.

**Comment by icemelon9** [comment]
Good point. I think it will slow down the task extraction time since it includes the codegen pass. I'll take a look and see if I can optimize it.

**Comment by icemelon9** [comment]
@comaniac @zhiics @tqchen Updated the PR. Could you help review it?

**Comment by comaniac** [comment]
LGTM. Now the VM compilation has two steps, `lower` and `codegen`. Since we only need to run lower when extracting AutoTVM tasks, the extraction time should be much shorter.

**Comment by icemelon9** [comment]
@zhiics Do you mean in the VMCompiler class?

**Comment by zhiics** [comment]
@icemelon9 yes, my bad.

**Comment by zhiics** [comment]
Thanks @icemelon9 @comaniac @wweic @tmoreau89

**Pull request merged**
