### PR TITLE
[Build][Windows] Fix Windows build by including cctype

### PR DESCRIPTION
**Pull request by soiferj**
The Windows build is currently broken with the error: `isdigit is not a member of standard`. It looks like `std::isdigit` is in header `<cctype>`. Including it fixes the build.

@tqchen @jmorrill could you take a look?

Also, is there an ETA to get the Azure build pipeline back up?

### CODE REVIEW

**Comment by jmorrill** [comment]
With the latest source from master, I do not get any build errors on the CMake generated tvm.sln.  

I am using Visual Studio 2019 (cl.exe version 19.23.28106.4).  What version are you using?

FWIW, your patch doesn't have any negative effects on my build ;)

**Comment by soiferj** [comment]
I'm using VS 2017 (cl version 19.16.27032.1). Where does your compiler get `std::isdigit` from?

I think we should still check this in for safety.

**Comment by jmorrill** [comment]
> I'm using VS 2017 (cl version 19.16.27032.1). Where does your compiler get `std::isdigit` from?

I believe mine is getting it from <cctype> also.  Could Microsoft have refactored some other std header in 2019 that inadvertently includes cctype? 

If that is the case I would agree with checking it in for safety.

**Comment by jmorrill** [comment]
I compiled file `\tvm\nnvm\src\top\tensor\transform.cc` with `/showIncludes` because it uses `std::isdigit `and found the only reference to `cctype` here:

```
1>Note: including file:    C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\include\string
1>Note: including file:     C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\include\cctype
```

Appears '`string`' is pulling `cctype` in with 2019?

**Comment by jmorrill** [comment]
Ok thats it.  `string` pulls in `cctype` in VS2019 and does not in 2017

Following builds in 2019 and does not in 2017.

```
#include <iostream>
#include <string>

int main()
{
    auto x = std::isdigit('5');
    std::cout << "Hello World!\n";
}
```

**Comment by soiferj** [comment]
Thanks a lot for the investigation - that's a useful finding. There should be no harm in adding this include :)

**Comment by soiferj** [comment]
@tqchen looks like there's a CI error impacting all PRs. Is this a known issue?

**Comment by tqchen** [comment]
Hmm, would due to CI overloaded and throttling and timeout, I will look into this.

**Comment by yzhliu** [comment]
Thanks @soiferj @jmorrill @tqchen

**Pull request merged**
