### PR TITLE
[Relay] Add more check to type relation.

### PR DESCRIPTION
**Pull request by MarisaKirisame**
Thanks for contributing to TVM!   Please refer to guideline https://docs.tvm.ai/contribute/ for useful information and tips. After the pull request is submitted, please request code reviews from [Reviewers](https://github.com/dmlc/tvm/blob/master/CONTRIBUTORS.md#reviewers).

### CODE REVIEW

**Comment by wweic** [comment]
@MarisaKirisame Should we revive this PR? It looks good after rebase.

**Comment by tqchen** [comment]
close for now due to inactive status, @wweic can you simply take over and send another patch?

**Comment by wweic** [comment]
@tqchen Yes, I'll send a follow up PR.

**Comment by MarisaKirisame** [comment]
@wweic sorry for the delay, I am busy submitting to ICML.

**Pull request closed without merging**
