### PR TITLE
[CI][Contrib] Add ACL docker installation

### PR DESCRIPTION
**Pull request by lhutton1**
This patch adds a cross-compiled ACL build to the ci_cpu dockerfile used for CI.

Change-Id: I66e1521ab553306bc7367b65acc0363e750f0211

### CODE REVIEW

**Comment by comaniac** [comment]
I'd suggest including `ubuntu_install_acl.sh` in this PR instead of in #5915, and let this PR in first to make sure #5915 could pass the CI.

**Comment by junrushao1994** [comment]
Just a dumb question. Do we need an ARM device to run ACL?

**Comment by lhutton1** [comment]
@junrushao1994 Yes ACL can only be used on Arm hardware. We've included this cross-build in the docker container to make it easier for anyone wanting to use ACL with RPC. They just copy across the libraries they need to the remote device rather than needing to worry about building a new container.

**Comment by tqchen** [comment]
Thanks @lhutton1 !

**Pull request merged**
