### PR TITLE
[Relay][Legalize] Legalize conv2d cuda for NHWC

### PR DESCRIPTION
**Pull request by apivovarov**
TFLite models use NHWC data layout.

In order to compile TFLite models for CUDA we need to legalize conv2d NHWC data layout for CUDA

### CODE REVIEW

**Comment by apivovarov** [comment]
@anijain2305 Can you have a look?

**Comment by anijain2305** [comment]
I was hoping that ConvertLayout PR gets merged in first. Then this will not be needed. @yzhliu

**Comment by apivovarov** [comment]
This PR is needed to compile TFLite models for CUDA. By design TFLite Relay frontend only supports NHWC target layout. Legalize is the fastest and easiest way to reuse existing NCHW operators for NHWC ops. Yes, it has overhead because of transpose ops before and after. But it still gives significant performance boost in comparison to CPU. e.g. `hand_landmark.tflite` takes 2ms on CUDA vs 27ms on CPU.
Without this PR I can not compile tflite models for CUDA.
This PR enables CUDA compilation for tflite models.
We can replace Legalize with more advanced (more performant) solution in future.

@vinx13 @FrozenGene Can you review this PR?

**Comment by anijain2305** [comment]
Convert Layout pass is merged. It might be worth it to try that.

**Pull request closed without merging**
