### PR TITLE
Add support for quant. mul operator in tflite frontend

### PR DESCRIPTION
**Pull request by inadob**
A test for qnn_mul has to be added when the qnn elemwise tests (#4282) get merged.

### CODE REVIEW

**Comment by inadob** [comment]
@kevinthesun @FrozenGene can you please take a look at this?

**Comment by cchung100m** [comment]
Hi @inadob 

Should we add the test case for `quant.mul `operator in tflite frontend?

**Comment by inadob** [comment]
@cchung100m 
I can add the tests on my own as soon as we agree on the #4282 implementation and merge it. I believe we can merge this patch now as there are a few other qnn operators that are already added relying on end-to-end testing by running the qnn models at the end of test_forward.py

**Comment by u99127** [comment]
LGTM, but you need an approver @anijain2305 , @FrozenGene ?

**Comment by anijain2305** [comment]
Hi @inadob , as your other PR is merged, will it be ok to add the test for mul op?
Sorry for the delay.

**Comment by tqchen** [comment]
Thanks @u99127 @inadob @cchung100m

**Pull request merged**
