### PR TITLE
Fix the values for test_fmod since it fails way too often otherwise

### PR DESCRIPTION
**Pull request by abergeron**
This fails more than 99% of the time on my machine with metal.

I've tested that seed on a couple of machines with OpenCL and CUDA to make sure they still work and the seem to do.

If there is a better way to approach this, I would love to hear it.

### CODE REVIEW

**Comment by tqchen** [comment]
@abergeron it would be great to understand where does the error comes from.

In this case, I guess that it comes from the near 1 rounding, we should do an amendment step such to avoid the numbers that are close to mod==1.

**Comment by abergeron** [comment]
From what I can seen the problem comes when result of the fmod() is very small.

It would happen for something like `20.0001 % 10`.

I'm not sure how to condition the random generation to avoid this problem, since we don't want the first number to be close to a multiple of the second number.

**Comment by tqchen** [comment]
This is a similiar we faced in the case like ceil/trunc

See an example here: https://github.com/apache/incubator-tvm/blob/master/topi/tests/python/test_topi_math.py#L57

**Comment by abergeron** [comment]
I dicovered that the problem is not that the values are too close it's that fmod() on metal doesn't have the same behaviour.

`fmod(x, y)` expands to `x – y * trunc(x/y)` instead of `x - y * floor(x/y)` like most other platforms.

So the solution is to change the codegen for fmod in metal I think.  I'll try to do that.

**Comment by abergeron** [comment]
Well that is not the problem since it only makes a difference if x or y is negative and we don't test that case.

**Comment by abergeron** [comment]
I've did something to fix the values so that the relative difference will never be too big.

I also have some code to replace the fmod expression on Metal, but that might be better in a separate PR.

**Pull request merged**
