### PR TITLE
[VTA][HotFix] Relay->VTA quantization fix

### PR DESCRIPTION
**Pull request by tmoreau89**
This addresses a compilation bug introduced by: https://github.com/apache/incubator-tvm/pull/4295

Other than interface changes to quantization pass (graph vs. module) it appears that this has broken quantization pass for VTA by inserting multiplication at the end of the layer when multiplication is not supported by VTA (and instead must rely on shift and add).

Investigation in progress.

@vinx13 @ZihengJiang

### CODE REVIEW

**Comment by tmoreau89** [comment]
@liangfu  This is the follow up to the fix you requested. Right now quantization breaks compilation to VTA, so this will require further investigation.

**Comment by vinx13** [comment]
@tmoreau89 Default opt_level has been changed to 2, batch_norm won't be folded during quantization, will this cause issue in vta?  You can still wrap `quantize` call within a `build_config` scope if that's needed. I did this because running calibration with bn folded caused some accuracy issues

**Comment by tmoreau89** [comment]
> batch_norm won't be folded during quantization, will this cause issue in vta

bingo - that's very likely the root issue which explains why we have multiplication in there

**Comment by tmoreau89** [comment]
@vinx13 looks like the `opt_level` fix does the trick. Issuing the fix right now.

**Comment by tmoreau89** [comment]
Hotfix should be ready for review.

**Comment by yzhliu** [comment]
Thanks @tmoreau89 @vinx13 @liangfu this is merged and will be included in v0.6.0 release

**Pull request merged**
