### PR TITLE
[topi][relay] new PR to re-add tan to TVM

### PR DESCRIPTION
**Pull request by notoraptor**
Following #4938 and #5017 , I re-submit this branch to add tan to TVM.

@kevinthesun @tqchen

### CODE REVIEW

**Comment by notoraptor** [comment]
Tests failed, but I don't know why.

**Comment by tqchen** [comment]
should be fixed by https://github.com/apache/incubator-tvm/pull/5029, please send a dummy commit(or rebase your code after that PR is merged)

**Comment by notoraptor** [comment]
Just amended the latest commit message to trigger checks.

**Comment by masahi** [comment]
Thanks @notoraptor

**Pull request merged**
