### PR TITLE
[Release] Add cma as a submodule

### PR DESCRIPTION
**Pull request by liangfu**
Following #4431, this PR removes cma module completely and adds it as a separate 3rdparty repo.

### CODE REVIEW

**Comment by tmoreau89** [comment]
@liangfu there is a CI error related to the new submodule, can you take a look?

**Comment by liangfu** [comment]
@tmoreau89 Oh, I think we might need two steps for resolving the conflict (I might be wrong). First, to remove cma directory completely. Second, to add the submodule. Let this PR take the first change.

**Comment by tqchen** [comment]
Unfortunately we cannot add it as a submodule either. Let us separate the kernel module out into a repo with instructions, and point to the repo to build the kernel module. The driver part can remain in the repo

**Comment by tqchen** [comment]
NOTE, the only thing we need to be careful about is the linux kernel module cma.c, which declared the binary driver's license to be GPL. The previous action to remove them was mainly act caution.

Background: we tried to package all source code in the 3rdparty during a release, if a folder contains potential GPL code, we cannot bundle it during release.

We need to determine the license of that source code, given that it includes linux header, would that makes the source code GPL, or is it OK to mark as MIT and in MODULE_LICENSE mark the driver as dual MIT and GPL.  

If we decided that the code can be MIT, then we can include it as part of 3rdparty source. Otherwise, we need to cut the code from the source release.

**Comment by liangfu** [comment]
Thanks for the explanation.
In this case, we shall only put application layer code into `3rdparty`, and only leave kernel module out of the repository. I would like to close this PR for now and put an update to fix the compilation error in a separate PR.

**Pull request closed without merging**
