### PR TITLE
[Docker] update onnx to 1.6 and torch to 1.4

### PR DESCRIPTION
**Pull request by masahi**
v1.4 was out last week and we are still at 1.2.

### CODE REVIEW

**Comment by tqchen** [comment]
Right now the CI update was blocked by https://github.com/apache/incubator-tvm/issues/4764, but we could build a torch update separately, depending on how quickly we can resolve the blocker.

**Comment by masahi** [comment]
There is no hurry, we can wait until mxnet issues are fixed.

**Comment by leandron** [comment]
Hi @masahi, I think it is also relevant to see whether these change I sent a few weeks ago (https://github.com/apache/incubator-tvm/pull/4632), can be reverted by updating torch to 1.4.

**Comment by masahi** [comment]
@leandron yes, torchvision 0.5 seems to be compatible with PIL 7.0. My installation was already 7.0.

```
In [5]: import PIL                                                                                                                                

In [6]: import torchvision                                                                                                                        

In [7]: PIL.__version__                                                                                                                           
Out[7]: '7.0.0'

In [8]: torchvision.__version__                                                                                                                   
Out[8]: '0.5.0'
```

does this answer your question?

**Comment by leandron** [comment]
Yes @masahi. Then, if you want, you can remove those `<7` in Pillow installations, in the context of this PR, so it is a self-contained torch update? I'm happy to review it for you.

**Comment by masahi** [comment]
ok reverted

**Comment by masahi** [comment]
hmm no idea why CI is failing. @leandron do you know what is going with sphinx issues?

**Comment by leandron** [comment]
Sorry @masahi , I don't know how that error is related to the Pillow dependency and couldn't find any related issue on sphinx.

**Comment by masahi** [comment]
ok CI is fixed. 

@tqchen since the update of MXNet seems to be having issues, and we want to test the [PyTorch frontend](https://github.com/apache/incubator-tvm/pull/4497) on the latest version, we want the PyTorch update to be built first.

**Comment by masahi** [comment]
@jwfromm have you tried pytorch 1.4 + onnx 1.6? So far I have no problem with this combo. I want to update onnx CI as well if possible.

**Comment by jwfromm** [comment]
I don't think I've tried that version combo. If it's working for you then I'd say let's update!

**Comment by masahi** [comment]
@jwfromm I posted what I think is the solution to "onnx segfault problem" at https://github.com/onnx/onnx/issues/2394. I encourage you to try it with pytorch 1.3 or 1.4.

**Comment by jwfromm** [comment]
You're right that importing onnx first resolves the issue. I tried it out with a few different pytorch and onnx version combinations and it runs fine with them all. Your explanation of the issue makes perfect sense as well. Funny that it was something so simple all along.

**Comment by masahi** [comment]
@tqchen we are ready to upgrade!

**Comment by tqchen** [comment]
OK, will report back in one to two days

**Comment by tqchen** [comment]
updates
- https://github.com/apache/incubator-tvm/pull/4827
- https://github.com/apache/incubator-tvm/pull/4826

**Comment by masahi** [comment]
@tqchen can we send torch 1.4 and onnx 1.6 dependent changes now that #4827 and #4826 were merged?

Also this PR can be closed.

**Comment by tqchen** [comment]
Only ci-cpu is updated atm. Let me know if we also need to update ci-cpu

**Comment by masahi** [comment]
does `ci-cpu` run on CI to test PRs? If so I cannot send  torch 1.4 and onnx 1.6 dependent changes.

**Comment by tqchen** [comment]
I believe it runs unit-tests but not integration(frontend tests)

**Pull request closed without merging**
