### PR TITLE
[PatternLang] Simplify Pattern API Implementations

### PR DESCRIPTION
**Pull request by comaniac**
Per discussion in this PR, here is the current changelog:

- Add `is_expr`, `is_constant`, `is_tuple`, and `is_tuple_get_item` APIs. As a result, users will not directly call `XXPattern` anymore.
- Rename `is_input` to `is_var` to against `is_constant`.
- Add dataflow pattern to doc/api.
- Fix all type annotations in `__init__.py`.

=== ORIGINAL DESCRIPTION ===

For each pattern node, we define `XXPattern` Python class for the FFI connection. We also define a user-friendly API such as `is_op` to have better user experience. Since `is_XX` APIs are just wrappers to the corresponding `XXPattern` class, this PR simplifies their implementations by turning the APIs to function aliases.

In addition, this PR also makes the following changes:

1. Add `is_expr`, `is_constant`, `is_tuple`, and `is_tuple_get_item` APIs. As a result, users will not directly call `XXPattern` anymore.
2. Rename `is_input` to `is_var` to against `is_constant`.

@mbrookhart I'm not quite sure if the second change makes sense to you or not so I intentionally separate it to the second commit. If you prefer `is_input`, I could just simply revert it.

Also cc @masahi

### CODE REVIEW

**Comment by mbrookhart** [comment]
I'm cool with the PR in general, but I'm a little skeptical of removing all of the doc strings for the syntactic sugar functions. Then again, I love the simplicity of it, so I'll think about it some more and give you some more feedback tomorrow morning.

**Comment by comaniac** [comment]
Hmm, docstring is a fair point. One solution I can think of is adding the API description in the docstring of the corresponding class. For example, adding “is_tuple” to the description of “TuplePattern”. I’ll think more tonight.

cc @tqchen in case you have any ideas.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by tqchen** [comment]
I agree that it is better to keep the docstring and add indirection in this case, as we did in many cases in the codebase

**Comment by comaniac** [comment]
OK I'll change them back then.

@mbrookhart how about `is_input` vs. `is_var`?

**Comment by mbrookhart** [comment]
:+1: I'm happy with that, it's more clear.

**Comment by mbrookhart** [comment]
Just to look at what this did to the API docs, I did a local build of the docs and realized I didn't get the pattern language into the API doc build :scream: @comaniac do you want to add that as part of this PR, or should I do another?

**Comment by comaniac** [comment]
Sure I can do that as well in this PR.

**Comment by comaniac** [comment]
Ah, this is a bit tricky. For type annotation, we should use `DFPattern` in this case. However, in Python 3.6, it parses the source file only once for type checking. It means if we define a class and refer it in the same file, the type checking won't find that class and will report type errors. While this issue has been fixed in Python 3.7, an official workaround is using a string for the class type. You can see https://stackoverflow.com/questions/15853469/putting-current-class-as-return-type-annotation for details.

Since TVM hasn't officially required Python 3.7+, I'd make sure the type annotation we are using is Python 3.6 compatible.

**Comment by masahi** [comment]
Thanks @comaniac @mbrookhart @tqchen

**Pull request merged**
