### PR TITLE
[Relay] Expose FunctionGetAttr to Python

### PR DESCRIPTION
**Pull request by soiferj**
Exposes `_expr.FunctionGetAttr` to Python. It's useful for writing custom composite function annotators.

@mbaret @tqchen @zhiics would you be able to take a look?

### CODE REVIEW

**Comment by zhiics** [comment]
@icemelon9 I think it's also in #4644 

https://github.com/apache/incubator-tvm/pull/4644/files#diff-4faeef95fcc3c0e22fa44e04de555ed3R280

**Comment by soiferj** [comment]
@zhiics could we get this in earlier? That PR has been open for a while and is much larger.

**Comment by mbaret** [comment]
I don't think there's a problem putting this in, it seems a valid standalone patch.

**Comment by zhiics** [comment]
@soiferj oh, btw, can you add a unit test?

**Comment by soiferj** [comment]
Sure, but I actually don't see a place where `set_attribute` is unit tested. Any suggestions for where to put it?

**Comment by zhiics** [comment]
https://github.com/apache/incubator-tvm/blob/master/tests/python/relay/test_ir_nodes.py

**Comment by soiferj** [comment]
Added test

**Comment by zhiics** [comment]
Thanks @soiferj @mbaret

**Pull request merged**
