### PR TITLE
[refactor][relay pass] Separate analysis and transform passes

### PR DESCRIPTION
**Pull request by zhiics**
As we are incrementally adding more and more passes to Relay. It makes sense to separate these passes into `analysis` and `transforms` namespaces. This makes the code cleaner and easy to find the pass that users want. In addition, commercial compilers like LLVM also organize the passes similarly.

This PR mainly separates the C++ side and creates `analysis` and `transforms` under passes. A followup PR will refactor the Python side.

Some discussion about this is here: https://discuss.tvm.ai/t/discuss-annotation-defined-subgraphs/5934/4

CC @tqchen @jroesch @icemelon9 @mbaret @comaniac

### CODE REVIEW

**Comment by tqchen** [comment]
Let us remove the pass folder and just do relay/transforms and relay/analysis

**Comment by zhiics** [comment]
@tqchen updated. PTAL. Thanks.

**Comment by tqchen** [comment]
@zhiics please rebase against the master

**Comment by icemelon9** [comment]
Thanks @zhiics @tqchen @comaniac. this is now merged.

**Pull request merged**
