### PR TITLE
[TARGET] enable amd_apu device on vulkan target

### PR DESCRIPTION
**Pull request by mei-ye**
Thanks for contributing to TVM!   Please refer to guideline https://tvm.apache.org/docs/contribute/ for useful information and tips. After the pull request is submitted, please request code reviews from [Reviewers](https://github.com/apache/incubator-tvm/blob/master/CONTRIBUTORS.md#reviewers) by @ them in the pull request thread.

enable amd_apu device on vulkan target.
@tqchen, @tmoreau89

### CODE REVIEW

**Comment by tqchen** [comment]
Thanks @mei-ye , assigning @tmoreau89  BTW, you do not have to reopen another PR for the updates, you can just force push to your original branch and the PR will be updated.

**Comment by tmoreau89** [comment]
Thanks you @mei-ye I'll close your other PR since it's a duplicate of this one.

One question: do you also intend on uploading logs into TopHub for the v1000?

**Comment by tmoreau89** [comment]
Never mind the other PR was already closed.

**Comment by tmoreau89** [comment]
Could you also add in the comments that there are a couple fixes applied to the Vulkan runtime? Because this PR could be technically split into two (bug fixes to Vulkan runtime for GPUs, and adding the V1000 target)

**Comment by mei-ye** [comment]
yes, I will check in log to  tophub after this.  This also fixes two bugs in vulkan runtime:
maxComputeWorkGroupInvocations:  the maximum total number of compute shader invocations in a single local workgroup.
maxComputeWorkGroupSize[3]: the maximum size of a local compute workgroup, per dimension.

**Comment by tmoreau89** [comment]
Thank you @mei-ye the PR has been merged

**Pull request merged**
