### PR TITLE
[CI] Add python setup script

### PR DESCRIPTION
**Pull request by tqchen**
To enable setup less stable python packages more quickly and avoid frequent docker update.

### CODE REVIEW

**Comment by tqchen** [comment]
cc @tmoreau89 @tkonolige

**Review by tmoreau89 — APPROVED** [review]
LGTM

**Review by ANSHUMAN87 — APPROVED** [review]
Thanks @tqchen , This is indeed required. :+1:

**Comment by ANSHUMAN87** [comment]
Just one thought, based on recent struggle in upgrading TF with a cascade effect. Should we have an option to override the existing dependency packages ? So that we can run the CI, with the intended dependency package without modifying the docker. Later on, once CI stable, we can change the docker.

**Comment by tqchen** [comment]
I believe pip install --user --upgrade would override the system installed package

**Comment by ANSHUMAN87** [comment]
Thanks @tqchen for confirming. I concur. :+1:

**Pull request merged**
