### PR TITLE
Consolidate RPC Context helper functions

### PR DESCRIPTION
**Pull request by areusch**
Small cleanup PR to move logic around building and examining RPC contexts into a single place. Helpful when building the pre-linked parameter PR (coming soon).

### CODE REVIEW

**Comment by areusch** [comment]
@tqchen

**Comment by areusch** [comment]
missed one thing, making draft.

**Comment by tqchen** [comment]
It would be helpful to keep these as an internal header for now, because the implementation of RPC should be hidden from the user.

**Comment by areusch** [comment]
@tqchen i was originally planning to do that but the implementation is already in this file under operator<<.

**Comment by tqchen** [comment]
OK, let us go with this then

**Review by tqchen — APPROVED** [review]

**Pull request merged**
