### PR TITLE
Revive the Rust + SGX refactor

### PR DESCRIPTION
**Pull request by jroesch**
Revive #2885 in order to unblock working on the Rust crates and runtime.

### CODE REVIEW

**Comment by jroesch** [comment]
cc @nhynes and @ehsanmok @robo-corg @adelbertc

**Comment by tqchen** [comment]
let us aim to merge it in a week

**Comment by tqchen** [comment]
Thanks @jroesch @nhynes !

**Comment by AlexYaoRuihao** [comment]
@nhynes Hello! This is Ruihao. Recently I'm working on moving Apache TVM into SGX environment by using Rust SGX SDK. However, by looking at commit histories, I find that you decided to switch Rust SGX SDK to Fortanix SGX EDP after this commit. I was trying to build the Rust SGX SDK version of TVM from commits before that commit but I was getting build errors. May I ask if there is a working version based on Rust SGX SDK? If so, I could continue working on it and patch it to the newest Rust SGX SDK version. I'll appreciate your response!

**Pull request merged**
