### PR TITLE
[ROCm] include mcpu and mtriple as target options

### PR DESCRIPTION
**Pull request by t-vi**
This fixes the ROCm backend after #6347 to also allow mcpu and mtriple attributes for ROCm target objects.

With this change, we can run the gpu_imagenet_bench.py again.

@junrushao1994 @masahi

### CODE REVIEW

**Comment by masahi** [comment]
Nice, just today I did a clean install of rocm 3.7, and wondered why the benchmark is broken. So timely for me :)

**Review by masahi — APPROVED** [review]

**Comment by tqchen** [comment]
@t-vi please rebase against the master to resolve conflicts

**Comment by junrushao1994** [comment]
Hmmm I think the issue has been fixed by #6369

**Comment by t-vi** [comment]
@junrushao1994 Right, thank you! @masahi @tqchen sorry for the noise. I had searched for rocm/mcpu patches but missed the more general one.

**Pull request closed without merging**
