### PR TITLE
[Relay][Frontend][Onnx] If Operator Support

### PR DESCRIPTION
**Pull request by jwfromm**
This surprisingly small PR adds support for the If operator in the Onnx frontend. This turned out to be a pretty direct conversion to relay!

### CODE REVIEW

**Comment by jwfromm** [comment]
@mbrookhart @masahi @tmoreau89 @soiferj can you guys take a look at this PR?

**Review by mbrookhart — APPROVED** [review]
LGTM

**Review by tmoreau89 — APPROVED** [review]
LGTM, thanks @jwfromm !

**Comment by masahi** [comment]
@jwfromm  please run CI again

**Comment by jwfromm** [comment]
I'm pretty confused why this is failing CI. It looks like on the GPU test, the onnxruntime produces the wrong value (getting a -2 instead of the correct value of 1) while TVM produces the proper result. It seems like on the CPU node, the test passes. I'm not able to replicate the error on my local GPU machine. Does anyone have any ideas (@masahi) why that might happen?

**Comment by masahi** [comment]
Maybe the old version of onnxruntime had a bug? ORT on CI is fairly old (v1.00) while the latest one is v1.5. You probably have a newer ORT locally.

**Comment by jwfromm** [comment]
Good point, I'll try to check out using v1.00. Thanks!

**Comment by masahi** [comment]
@jwfromm something is wrong with CI

**Comment by jwfromm** [comment]
Sorry for the delay. It seems like the only path forward on this for now is to disable GPU tests until onnxruntime is updated to a newer version.

**Comment by jwfromm** [comment]
@masahi, I ended up removing onnxruntime from the if test for now. Since the correct result in this case is very clear, there's not much need to generate with onnxruntime. Once we update to a newer ort version I'll switch back.

**Comment by masahi** [comment]
thanks @jwfromm @mbrookhart @tmoreau89

**Pull request merged**
