### PR TITLE
[RELAY][QNN]Add support for QNN Div operator

### PR DESCRIPTION
**Pull request by siju-samuel**
Adding support for QNN Div operator

@anijain2305 @zhiics  Please help to review this PR

Thanks for contributing to TVM!   Please refer to guideline https://docs.tvm.ai/contribute/ for useful information and tips. After the pull request is submitted, please request code reviews from [Reviewers](https://github.com/apache/incubator-tvm/blob/master/CONTRIBUTORS.md#reviewers) by @ them in the pull request thread.

### CODE REVIEW

**Comment by anijain2305** [comment]
Hi @siju-samuel Thanks for the effort. Can you please give a usecase where we use quantized division? is there any quantized division operator?

**Comment by siju-samuel** [comment]
HI @anijain2305 I was trying to run quantized Mobilenetv3, it has a hard_swish node, which will need a div op.

image

**Comment by anijain2305** [comment]
Thanks @siju-samuel I will read it and review the PR today. Thanks for increasing the coverage :)

**Comment by masahi** [comment]
@siju-samuel What frontend are you using? Torch frontend can already convert and run quantized mobilnet v3. I didn't have a need for QNN div op. For hswish, Torch uses `quantized::mul_scalar` op, which is a scaling by 1/6. 

For scaling by positive scalar, I didn't have to do anything. Just changing the "interpretation" of the input quantized tensor is all I needed. See 
https://github.com/apache/incubator-tvm/blob/03cbf78e3e8cc910c5a9c95cd3fcafa19959644f/python/tvm/relay/frontend/qnn_torch.py#L697-L701

**Comment by siju-samuel** [comment]
@masahi  Thanks a lot for your suggestion. i was using tflite frontend. As of now i used dequantize/quantize methods and i was able to run mobilenetv3 models, there are variations in output, still accuracy is not hit very badly.  
We can use `mul_scalar` method since its scalar, still i suggest, we can keep the `qnn.div` op for non scalar multiplications.

**Pull request closed without merging**
