### PR TITLE
More CHECK to ICHECK

### PR DESCRIPTION
**Pull request by rkimball**

### CODE REVIEW

**Comment by jroesch** [comment]
The NNVM code is mostly dead code but looks good to me.

**Review by jroesch — APPROVED** [review]

**Comment by ptrendx** [comment]
I don't think change to the NNVM directory is right - NNVM does not rely on the rest of TVM so it does not know about `ICHECK` macros and compiling it results in a bunch of `not declared` errors.

**Comment by tqchen** [comment]
@ptrendx you are right, please send another PR to revert the change in NNVM part

**Comment by ptrendx** [comment]
@tqchen Thanks, I just did (#7255).

**Pull request merged**
