### PR TITLE
[Arith] Constant cancellation added for subtraction

### PR DESCRIPTION
**Pull request by ANSHUMAN87**
Additional constant cancellation added with few useful test cases.

cc @tqchen , @yzhliu

### CODE REVIEW

**Comment by tqchen** [comment]
The canonicalization based rules should already be sufficient for these cases, so if there is no explicit motivating usecases, it would be useful to keep things simple and not including the additional change

**Comment by ANSHUMAN87** [comment]
@tqchen : Thanks for your clear feedback! I did also have similar concerns here. These are some trivial issues I observed during my analysis. Now I understand canonicalization will resolve these.

But keeping that in mind, I found some redundant rules still exists in rewrite simplify. 
So as you see, the clear distinction is missing.
So if it is possible, would you please help me understand what kind of rules should be part of rewrite simplify and which should be handled in canonical simplify. 
This will help me put my future PR in right direction. TIA!

**Comment by tqchen** [comment]
We are using the two systems in a complementary way. Given that the simplifier is a core piece of the system and can easily introduce regressions, it is preferred to be careful and only make changes when we find a concrete motivating cases.

**Comment by ANSHUMAN87** [comment]
Okay I got the point. Thanks!
So will it be correct to assume that the cases which are not handled by canonicalization should be added as rule in rewrite or it is other way around? 

I am sorry, please bear with me in understanding it, as I found many discrepancies when I am using both together in simplify() .

**Comment by tqchen** [comment]
yes, it would be great to also backed by a motivating example(e.g. the need to simplify indices for conv2d operator). Since we are not building a generic simplifier that resolves all complications. Closing this for now

**Pull request closed without merging**
