### PR TITLE
[REFACTOR][PY][API-Change] Polish tvm.runtime, tvm.runtime.module API update

### PR DESCRIPTION
**Pull request by tqchen**
This PR updates the tvm.runtime to use the new FFI style.

- Remove top-level tvm.module to avoid confusion between runtime.Module and IRModule
- API changes wrt to runtime.Module
  - tvm.module.load -> tvm.runtime.load_module
  - tvm.module.enabled -> tvm.runtime.enabled
  - tvm.module.system_lib -> tvm.runtime.system_lib
- Remove dep on api_internal from runtime.

### CODE REVIEW

**Comment by tqchen** [comment]
cc @FrozenGene @icemelon9 @yzhliu @ZihengJiang

**Comment by FrozenGene** [comment]
As https://github.com/apache/incubator-tvm/pull/4564 is merged, but the doc still use `tvm.module.load`, would you change to `tvm.runtime.load` too?

**Comment by tqchen** [comment]
@FrozenGene Good catch, i have updated the PR to reflect the lastest set of changes

**Comment by kparzysz-quic** [comment]
The file `jvm/core/src/main/java/org/apache/tvm/Module.java` still uses old names.  This broke the Java RPC app.

**Comment by tqchen** [comment]
@kparzysz-quic Thanks for the catch, here is a patch https://github.com/apache/incubator-tvm/pull/4871

**Pull request merged**
