### PR TITLE
[PY][FFI] Refactor runtime.String to subclass str

### PR DESCRIPTION
**Pull request by tqchen**
To make runtime.String to work as naturally as possible in the python side,
we make it sub-class the python's str object. Note that however, we cannot
sub-class Object at the same time due to python's type layout constraint(
cannot subclass from multiple classes with slots).

We introduce a PyNativeObject class to handle this kind of object sub-classing.

### CODE REVIEW

**Comment by tqchen** [comment]
cc @zhiics @icemelon9 @jroesch 

This is a PR that helps to prepare the std::string->String migration.

**Comment by icemelon9** [comment]
Thanks @tqchen @zhiics

**Comment by junrushao1994** [comment]
If on python side we pass a `runtime::String` to packed function, whose signature uses `std::string` instead, is this case un-supported in this PR?

**Comment by tqchen** [comment]
No, we don't support auto convert from String to std::string, we do want to convert most user facing  packed api to use String though so no conversion is needed

**Pull request merged**
