### PR TITLE
[TARGET] add amd_gpu target

### PR DESCRIPTION
**Pull request by mei-ye**
Thanks for contributing to TVM!   Please refer to guideline https://tvm.apache.org/docs/contribute/ for useful information and tips. After the pull request is submitted, please request code reviews from [Reviewers](https://github.com/apache/incubator-tvm/blob/master/CONTRIBUTORS.md#reviewers) by @ them in the pull request thread.
This target uses vulkan runtime.   Once this change is pushed into upstream, a log will be added to tophub. This change contains minimum target-specific codes.

### CODE REVIEW

**Comment by mei-ye** [comment]
@tqchen

**Comment by tqchen** [comment]
Thanks @mei-ye . My understanding is that this is for AMD integrated cards. Given that the programming model is still vulkan, we might want to discuss how to distinguish it from the rocm part. Perhaps an alternative way is to directly use `vulkan -model=v1000`, so that we can still have model specific optimizations(like the case of mali in ARM) while not introduce a new target key.

**Comment by tmoreau89** [comment]
@mei-ye great to see this contribution on getting support for the AMD APU! @tqchen 's comments are correct, ideally we would want to use `vulkan -device=apu` target with perhaps the optional `-model=gfx900` flag to specify the opencl or vulkan backend (it might help with opencl).

**Comment by mei-ye** [comment]
Tianqi and Thierry,

Thanks for our advise.  I can see your points,  especially the benefit of supporting both vulkan and opencl.  But I also have some concerns:
1. We want to get rid of data movements between CPU and GPU.  Do we need a new runtime?  If yes, having a new target will be more convenient.
2.  It looks like target-dependent condition checking codes are heavily relying on string match for target names.   Without adding a new target, we will need to check both target name and device_name.   Is device_name available throughout TVM?

**Comment by mei-ye** [comment]
Also, without a new target, we will need to merge logs for all APU models into opencl_v0.xx.log

**Comment by tqchen** [comment]
We don't need a new target key for autotvm and logs, see the case for mali https://github.com/uwsampl/tophub/blob/master/tophub/mali_v0.04.log The device is preserved throughout the tvm

In terms of the future runtime data sharing between cpu and GPU. I think that it can be solved directly by extending the opencl or vulkan runtime to support the shared memory, likely the memory will become vulkan_shared, like the cpu_pinned memory in the CUDA.

**Comment by mei-ye** [comment]
yes, we don't need a new target key for autotvm log, but we will need opencl_vxx.log to combine logs for different devices, right?

**Comment by tqchen** [comment]
See the example case above(the link to mali log) which uses the opencl, but have a separate log by itself

**Pull request closed without merging**
