### PR TITLE
[CI] Fix error guard to detect tutorial problems

### PR DESCRIPTION
**Pull request by tqchen**
This PR fixes an error guard during the documentation build step.

- Temporary disables VTA frontend tutorial due to
  the regression of deploy_detection

### CODE REVIEW

**Comment by tqchen** [comment]
cc @tmoreau89

**Comment by tmoreau89** [comment]
@tqchen is it possible to keep testing the classification tutorial and leave the detection example out? This will ensure that the end to end compilation flow for at least ResNet remains exercised.

**Comment by tqchen** [comment]
cc @tmoreau89 OK i only disabled the detection example out by moving it to a separate folder, we can move it back later

**Comment by tqchen** [comment]
move to #6377

**Pull request closed without merging**
