### PR TITLE
[Fix,Conda] update conda download url

### PR DESCRIPTION
**Pull request by shibuiwilliam**
What: a small change to update conda download url.

Thanks for contributing to TVM!   Please refer to guideline https://tvm.apache.org/docs/contribute/ for useful information and tips. After the pull request is submitted, please request code reviews from [Reviewers](https://github.com/apache/incubator-tvm/blob/master/CONTRIBUTORS.md#reviewers) by @ them in the pull request thread.

### CODE REVIEW

**Comment by shibuiwilliam** [comment]
@tqchen Please take a look at it, thanks!

**Comment by junrushao1994** [comment]
May I ask what the difference between the urls? Thanks!

**Comment by shibuiwilliam** [comment]
> May I ask what the difference is between the urls? Thanks!

The domain is different. Changing from `repo.continuum.io` to `repo.anaconda.com`.

Docker build fails with unable to download the miniconda installer with the current url `https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh` .
Changing to the conda's current url, `https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh` , succeeds.

**Review by leandron — APPROVED** [review]
This looks correct, and I think this PR is needed.

When  you `wget https://repo.continuum.io`, you get an HTTP 301 and gets redirected to the new address `repo.anaconda.com`, so I think we better to use the up-to-date URL for the repo.
```
wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
--2020-10-26 11:02:38--  https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
Resolving repo.continuum.io (repo.continuum.io)... 104.18.200.79, 104.18.201.79, 2606:4700::6812:c94f, ...
Connecting to repo.continuum.io (repo.continuum.io)|104.18.200.79|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
...
```

**Review by tqchen — APPROVED** [review]

**Comment by tqchen** [comment]
Thanks @leandron @junrushao1994 @shibuiwilliam !

**Comment by shibuiwilliam** [comment]
Thanks!

**Pull request merged**
