### PR TITLE
[WIP] Clean up AMD Code Gen

### PR DESCRIPTION
**Pull request by petrex**
AMD GPU codegen supports LLVM 9/10 at this moment. Motivation is to support Navi (bc not compatible with the previous AMD LLVM backend); hence dropping the unused codes in this PR.

Note that Navi support requires LLVM9+ && ROCm 2.8+. I will document this and create a docker image in separate PRs.

### CODE REVIEW

**Comment by petrex** [comment]
need to skip AMD build on LLVM 4/7/8 in CI... maybe save some compute as well...

**Comment by masahi** [comment]
@petrex btw we have the rocm channel on our slack. We can discuss rocm related issues with @t-vi 
 there if you like. We used that channel when we were bringing up our rocm backend.

**Comment by tqchen** [comment]
any status on this pr?

**Comment by tqchen** [comment]
@masahi @petrex please followup. @masahi would you be able to take it over and try to close this PR

**Comment by t-vi** [comment]
I wonder whether the cleanup we're doing here is in fact worth it.
So what happens is the PR wants to remove LLVM < 6 compatibility because we effectively cannot use it with ROCm.
If we wanted to make this cleanup, we could make the AMDGPU codegen conditional on
- LLVM >= 6 (which doesn't really make sense given that we want to clean up this condition),
- make it dependent on USE_ROCM, but that would reduce the AMDGPU/ROCm coverage of "at least it copiles CI", which I would find regrettable (in an ideal world, I'd rather start a discussion on how to include ROCM in the CI, at least keeping it building should be possible even without hardware, but we might also want to see how much hardware we would need and how to see about this).

BTW: With the same argument, we could also drop the < 9 and only keep the >= 9 bits because LLVM < 8 will crash with NAVI bitcode.

**Comment by tqchen** [comment]
@t-vi good points. Given that this PR is inactive atm, let us close it for now and discuss new alternatives. I think it is good to keep things backward when possible and have a clear error message when we need higher versions of LLVM

**Pull request closed without merging**
