### PR TITLE
[WIP][Relay][Frontend] Chainer frontend introduced

### PR DESCRIPTION
**Pull request by ANSHUMAN87**
Introducing new frontend  **_Chainer_** among other Relay frontends.

Below is TODO list for this PR:
- [x] Support one complete model import from Chainer to TVM(Say VGG16) along with test cases.
- [ ] Tutorial to use Chainer frontend.
- [ ] Support at least five different models available under ChainerCV publishings.

@tqchen , @FrozenGene , @masahi , @zhiics , @kazum, @Huyuwei, @MarisaKirisame  : Welcome for review. TIA!

### CODE REVIEW

**Comment by masahi** [comment]
You should first send a RFC on why you want to add this frontend. I don't think it is a good idea for the following reasons:

* Chainer is now in maintenance mode
* We already have ONNX and PyTorch frontend. Existing Chainer users are being encouraged to switch to PyTorch, so they can use either frontend

**Comment by tqchen** [comment]
I agree that given the current support of chainer, perhaps we should not introduce this frontend.

**Comment by ANSHUMAN87** [comment]
@tqchen, @masahi: Thanks for your feedback. However I couldn't not agree completely on the reasonings shared by masahi. 

Please find my response accordingly. 

I know the current support of ONNX, but is that not the case for many of the frontends already supported now?

Also if the CI slowness is the worry, then we should come up with a solution for that. We should not restrict to fewer frontends. 

As I see, the numerous user of chainer framework will get benefitted by this frontends, even though they are encouraged to switch to other framework.

As the concern raised for development and maintenance, definitely I will take care of that through constant effort. Also one point, the maintenance effort is proportional to no of active user(as the requirement also increases with that).

My opinion is this frontend will attract more user towards TVM. Thanks!

**Comment by tqchen** [comment]
@ANSHUMAN87 feel free to send an RFC to the discuss forum to get more feedbacks

**Comment by masahi** [comment]
See https://discuss.tvm.ai/t/discuss-adding-a-pytorch-frontend/5026 for a RFC on adding the PyTorch backend. Yes, discussion with respect to ONNX is common when adding a new frontend, and the PyTorch RFC above gave some reasons adding the PyTorch frontend could be justified. You want to have similar story for Chainer, more specific than "Chainer users would benefit" or  "attracting more users" or

**Comment by FrozenGene** [comment]
I agree some points of @ANSHUMAN87 .  TVM is so attractive, I think one reason is we are very open and happy to provide stage for them . However, given current status of chainer, we are more willing to discuss more detail about it in RFC. Like whether we should introduce it into TVM, how to support it better and so on.

**Comment by ANSHUMAN87** [comment]
@tqchen , @masahi , @FrozenGene : I am really thankful for your responses. I will definitely raise RFC very soon(mostly within 2 days) for this feature and obtain all your expert opinions. TIA!

NOTE: Because of working timezone differences. You might see my response little delayed. However i will ensure my best effort to respond all your posts as early as possible. Please bear with me for that.

**Comment by ANSHUMAN87** [comment]
[RFC](https://discuss.tvm.ai/t/introduce-new-frontend-for-chainer/6129) raised.

**Comment by ANSHUMAN87** [comment]
@tqchen : This PR is now ready with one complete model VGG16 importing from Chainer. Same test case is also added.
But when i check the CI report, it fails because of missing Chainer package. Can you please help me on resolving this issue? TIA!

**Pull request closed without merging**
