### PR TITLE
[TIR][REFACTOR] std::string -> String Migration in TIR nodes

### PR DESCRIPTION
**Pull request by cchung100m**
Hi @tqchen @zhiics @jroesch 

Following issue #5490 , this PR is working for `std::string` -> `String` Migration in TIR nodes. I would appreciate if you can help to review it, many thanks.

### CODE REVIEW

**Comment by jroesch** [comment]
Let me know when its ready for review.

**Comment by cchung100m** [comment]
Hi @jroesch 

Thanks for the reply.

I will change this PR to draft because I am still fighting the build failed and other errors.

**Comment by cchung100m** [comment]
Hi @jroesch 

I would appreciate if you are available to review/merge it, thanks.

**Comment by jroesch** [comment]
Thanks! LGTM

**Comment by cchung100m** [comment]
Thanks to @jroesch :)

**Pull request merged**
