### PR TITLE
Fix bug in processing script

### PR DESCRIPTION
**Pull request by hogepodge**
The argsort command returns a new array that is the sorted
index rather than a new sorted value array. This patch
stores the sorted index in a new variable and uses it to
reference the predicted values.

### CODE REVIEW

**Comment by hogepodge** [comment]
@mbrookhart

**Comment by comaniac** [comment]
It's a bit confusing to assign index to `scores`. How about something like

```python
ranks = np.argsort(scores)[::-1]
for rank in ranks[0:5]:
    print("class='%s' with probability=%f" % (labels[rank], scores[rank]))
```

**Comment by hogepodge** [comment]
Thanks, updated

**Review by comaniac — APPROVED** [review]

**Comment by comaniac** [comment]
Thanks @hogepodge

**Pull request merged**
