### PR TITLE
[Rust] change Context.device_id from usize to c_int (#6528)

### PR DESCRIPTION
**Pull request by intheworld**

### CODE REVIEW

**Comment by zhiics** [comment]
cc @jroesch @mwillsey

**Comment by mwillsey** [comment]
@intheworld could you say a little more about why this change is needed? I think the point of Context is that it's a "safer" Rust version of TVMContext. As long as you check that `device_id` is positive, the conversion should be fine (typed conversion, not just casting). I'd rather have usize (or u32) on the Rust side, since you don't have to worry about negative device ids

**Comment by tqchen** [comment]
I think one potential concern is what will happen if we load a DLContext from the memory, and perhaps it would be better to make sure the data structure is consistent with the FFI.

**Comment by intheworld** [comment]
> @intheworld could you say a little more about why this change is needed? I think the point of Context is that it's a "safer" Rust version of DLContext. As long as you check that `device_id` is positive, the conversion should be fine (typed conversion, not just casting). I'd rather have usize (or u32) on the Rust side, since you don't have to worry about negative device ids

I see the following code in PackedFunc.
impl_pod_value!(Int, i64, [i8, i16, i32, i64, isize]);
impl_pod_value!(UInt, i64, [u8, u16, u32, u64, usize]);

usize will be passed in i64, but considered as UInt, which caused type-check of device_id fail. Which I have mentioned in issue #6528. 

In dlpack.h, 
typedef struct {
  /*! \brief The device type used in the device. */
  DLDeviceType device_type;
  /*! \brief The device index */
  int device_id;
} DLContext;

My thought is to make the type consistent.

**Comment by tqchen** [comment]
@intheworld please fix the rust format lint error as indicated by the CI

**Comment by jroesch** [comment]
@intheworld we have repaired the ResNet example on #6563 to the best of my knowledge does no longer exhibits this issue. The previous iteration of the Rust bindings pre-object system used a large amount of unsafe code which Max and I have tried to audit and remove. 

Can you provide a reproducible test case to accompany the change, even if we do so I don't believe c_int is the right type to put in the Rust interface as the issue you described only sounds like an issue between signed and unsigned values. 

In general it is bad form in Rust to expose C types in safe Rust interfaces vs. native Rust types, given we convert the Rust Context to DLContext when passing across the boundaries I don't clearly see why this should be an issue?

**Comment by intheworld** [comment]
@jroesch I have reviewed #6563, and it looks good to me. I will abandon this PR. Thanks a lot!

**Pull request closed without merging**
