### PR TITLE
[runtime][cublas] fix typo

### PR DESCRIPTION
**Pull request by cloud-mxd**
Thanks for contributing to TVM!   Please refer to guideline https://tvm.apache.org/docs/contribute/ for useful information and tips. After the pull request is submitted, please request code reviews from [Reviewers](https://github.com/apache/incubator-tvm/blob/master/CONTRIBUTORS.md#reviewers) by @ them in the pull request thread.

### CODE REVIEW

**Comment by cloud-mxd** [comment]
image

**Comment by cloud-mxd** [comment]
cc @lanchongyizu

**Comment by cloud-mxd** [comment]
@tqchen Can merge ？

**Comment by FrozenGene** [comment]
Thanks @cloud-mxd @siju-samuel

**Pull request merged**
