### PR TITLE
[Arith] ExtendedEuclidean merge impl to int_operator

### PR DESCRIPTION
**Pull request by ANSHUMAN87**
Refer #5384

@tqchen , @yzhliu : Please help review. Thanks!

### CODE REVIEW

**Comment by tqchen** [comment]
Given that the original issue was assigned to @yzhliu and the change also relates to https://github.com/apache/incubator-tvm/pull/5618. Let us wait @yzhliu to address it there

**Comment by ANSHUMAN87** [comment]
@yzhliu : Gentle ping!

**Comment by ANSHUMAN87** [comment]
@yzhliu : Thanks! CI is green, now!

**Comment by tqchen** [comment]
Thanks @ANSHUMAN87 , @yzhliu please followup with other changes including gcd and lcm in the another PR(e.g #5618.)

**Pull request merged**
