### PR TITLE
[WIP] Support int64 indices

### PR DESCRIPTION
**Pull request by kazum**
When fusing concat op to strided_slice/take/gather_nd, we get a type mismatch error if the type of indices is int64.

@yzhliu @kevinthesun @yongwww, could you help review?

### CODE REVIEW

**Comment by tqchen** [comment]
also cc @hzfan

**Comment by hzfan** [comment]
It would be great if we can support i64 indices which does not fit into i32 (like 2^60). Simply casting i64 to i32 does not work in this scenario. A possible alternative is to modify the `GetShape` function (https://github.com/apache/incubator-tvm/blob/master/src/relay/backend/compile_engine.cc#L102) like #5235. Could you give it a try?

**Comment by tqchen** [comment]
I agree that supporting i64 indices is a better idea

**Comment by kazum** [comment]
Okay, I'll give it a try.

**Comment by tqchen** [comment]
@kazum let us know if it is ready for review

**Comment by kazum** [comment]
@hzfan @tqchen  Sorry, I'll withdraw this PR.  Supporting i64 indices needs more changes than what I expected, and it would take much time for me to finish it.  Rather than holding the PR for a long time, I'll close this PR for now so that other developers can have a chance to implement it instead.

@hzfan, if you'd send a PR for this, I'd be happy to review it :)

**Pull request closed without merging**
