### PR TITLE
[CodeGen] Add build config option disable_assert to control whether to generate assert

### PR DESCRIPTION
**Pull request by FrozenGene**
Currently, we will generate assert stmt, which will make us see many assert stmt in LLVM IR. It will Interference our focus. 

The usage is simple:
```python
with tvm.build_config(disable_assert=True):
    tvm.build(...)
```
disable_assert default value is false.

Related discuss:
https://discuss.tvm.ai/t/disable-assert-in-runtime/2152/4

@tqchen

### CODE REVIEW

**Comment by FrozenGene** [comment]
> Actually, it would be great if we can do it at an earlier point, and add a pass to remove assert. This will allow the same pass to work for both LLVM and C backend

@tqchen  I tried to implement one IRPass (like SkipAssert) to remove assert in `BuildStmt`  https://github.com/apache/incubator-tvm/blob/master/src/codegen/build_module.cc#L389. However, I find that during `lower` https://github.com/apache/incubator-tvm/blob/master/src/codegen/build_module.cc#L444, we will still produce AssertStmt internally. Do you have any good suggestion?

For CodeGenC, one way could be like CodeGenCPU:
```c
void CodeGenC::VisitStmt_(const AssertStmt* op) {
    if (!BuildConfig::Current()->disable_assert) {
        std::string cond = PrintExpr(op->condition);
        PrintIndent();
        if (const auto* str = op->message.as<StringImm>()) {
            // GLOG style check
           stream << "CHECK(" << cond << ") << \"" << str->value << "\";\n";
        } else {
           stream << "assert(" << cond << ");\n";
       }
       this->PrintStmt(op->body);
    }
}
```

**Comment by tqchen** [comment]
We can do it one step before the final codegen

**Comment by FrozenGene** [comment]
> We can do it one step before the final codegen

@tqchen please review it again. I add one pass `SkipAssert` called on the final codegen in `Build` function.

**Comment by tqchen** [comment]
Thanks @FrozenGene !

**Pull request merged**
