### PR TITLE
[VTA][TSIM] Enable TSIM CI Testing

### PR DESCRIPTION
**Pull request by liangfu**
This PR intends to enable testing Chisel VTA design with the help of TSIM.

### CODE REVIEW

**Comment by yzhliu** [comment]
@tmoreau89 could you take a look?

**Comment by tmoreau89** [comment]
@liangfu  it seems like there are some errors in the CI; were you able to run the unit tests locally? You may have to test it and run it into the CI docker container. You may want to try it locally on your machine. BTW, the reason I had to comment out these lines of code is because the tests in the docker was causing some issues. I can spend cycles help debug what's wrong.

**Comment by liangfu** [comment]
It seems to me that Chisel dependencies are handled properly already, except for fixing the `sbt` version to 1.1.1 in installing sbt throught apt, so that an update to sbt version is no longer necessary.

@tmoreau89 Yes, I'm able to run the unit tests locally. The error reported in the CI seems to be related to the build configuration. I will put on an update once I found the root cause.

**Comment by tmoreau89** [comment]
thanks @liangfu

**Comment by liangfu** [comment]
Hi @tmoreau89 , I have updated the [docker/install/ubuntu_install_chisel.sh](https://github.com/apache/incubator-tvm/pull/4407/files#diff-7c91185ffa66a3176f04513f2ef7df33), do you have any idea how to reflect the change in the CI pipeline?

**Comment by tmoreau89** [comment]
Thanks @liangfu ; was the test running successfully on the image? We'll need to get @tqchen to update the image registry.

**Comment by tqchen** [comment]
Thanks @liangfu Please send a PR separately for the docker update. Then we can enable tests

**Comment by liangfu** [comment]
Some recent changes made the unit tests unsuccessful.

**Comment by liangfu** [comment]
@tmoreau89 As shown in [my last commit](https://ci.tvm.ai/blue/organizations/jenkins/tvm/detail/PR-4407/21/pipeline/37) , the complete VTA test are successful with TSIM backend.

The latest CI log is reporting failure because we have verilator and sbt installed on docker image v0.55 , but not on v0.52 .

**Comment by tmoreau89** [comment]
Thanks for pushing this through to the finish line @liangfu!  Can we update the docker image used for CI testing?

**Comment by tmoreau89** [comment]
Also do you mind referencing the PR that updates the docker image for future reference?

**Comment by liangfu** [comment]
> Also do you mind referencing the PR that updates the docker image for future reference?

Please refer to #4674 for installing verilator and sbt, #4675 for installing their dependencies, and #4677 for using the new image in CI.

**Comment by tmoreau89** [comment]
Cool, thanks. Since the PRs have been merged, is there a reason why we are still using the old docker image which causes CI to fail?

**Comment by liangfu** [comment]
I think docker image v0.52 is for i386, and it has no svt and verilator install. Previous docker update v0.55 is for x86-64.

**Comment by tmoreau89** [comment]
Oh so you're saying that we cannot run tsim tests on `i386` then? Should we disable the tsim tests for i386 then?

**Comment by liangfu** [comment]
> Oh so you're saying that we cannot run tsim tests on `i386` then? Should we disable the tsim tests for i386 then?

Yes, but I'm not quite sure about how to do this.

**Comment by tmoreau89** [comment]
I can suggest the following: we can have a `task_python_vta_fsim.sh` and a `task_python_vta_tsim.sh` script that are each separate. One thing we'll need to do before executing tests is to add the `cp vta/config/fsim_sample.json vta/config/vta_config.json` or `cp vta/config/tsim_sample.json vta/config/vta_config.json`first wether we execute fsim or tsim respectively. This ensures that if someone re-orders the tests, functionality won't be affected...

**Comment by liangfu** [comment]
Sure, let's follow this approach.

**Comment by tmoreau89** [comment]
@liangfu great! Can you also update the jenkins file? Please grep for `task_python_vta.sh` in the Jenkins file, and for `i386` keep the `fsim` tests, while for `x86_64` add both. Thanks!

**Comment by liangfu** [comment]
@tmoreau89 Jenkinsfile has been revised, but why Jenkins is still evaluating `task_python_vta.sh` ?

**Comment by tmoreau89** [comment]
hmmm that's odd; try re-triggering it one more time?

**Comment by liangfu** [comment]
I come to understand the reason now, since PR #4677 change the image to v0.55, but Jenkins still runs on [v0.54](https://ci.tvm.ai/blue/organizations/jenkins/tvm/detail/PR-4677/1/pipeline/37) on that PR.

**Comment by tmoreau89** [comment]
thank you @liangfu the PR has been merged!

**Pull request merged**
