### PR TITLE
[RELAY][BYOC] Preserve type information in Merge Composite

### PR DESCRIPTION
**Pull request by mbaret**
Keep the type information when extracting patterns so that it can be used as part of 'check' functions. The is needed for cases where a pattern may only be supported if tensors are of certain shapes/sizes.

### CODE REVIEW

**Comment by mbaret** [comment]
cc @comaniac @zhiics @masahi

**Comment by mbaret** [comment]
Not sure I understand why the tests have failed, looks tflite related.

**Comment by tqchen** [comment]
https://github.com/apache/incubator-tvm/pull/5641

**Comment by masahi** [comment]
@mbaret please run the CI again, this time it should work.

**Comment by masahi** [comment]
Thanks @mbaret @comaniac @zhiics

**Pull request merged**
