### PR TITLE
[TVMC] use common function to obtain target from --target value on 'tvmc compile'

### PR DESCRIPTION
**Pull request by leandron**
This solves a `TODO` item on TVMC, using a common function to obtain the target from `--target` in the command line. The common function is already used in `tvmc tune`.

cc @comaniac @FrozenGene

### CODE REVIEW

**Review by comaniac — APPROVED** [review]
LGTM. Can you also file an issue to list all the TODOs we discussed in previous PRs so that we can easily track the status? Thanks.

**Comment by leandron** [comment]
> LGTM. Can you also file an issue to list all the TODOs we discussed in previous PRs so that we can easily track the status? Thanks.

I raised #6792 to cover the pending items on TVMC backlog.

**Comment by leandron** [comment]
If you're ok with the issue I filed to tackle backlog items, can we merge this one?

**Comment by comaniac** [comment]
Thanks @leandron

**Pull request merged**
