### PR TITLE
Factor out import of common tflite.Operator in tflite frontend.

### PR DESCRIPTION
**Pull request by u99127**
Common out tflite.Operator in the tflite frontend. 

@FrozenGene , could you please review this. 

Thanks,
Ramana

### CODE REVIEW

**Comment by u99127** [comment]
hmm, not sure how it passed my test run with linting before I submitted this.

**Comment by siju-samuel** [comment]
@u99127 I think this PR will create unnecessary dependancy with tflite package and tvm. With this change you mandatorily need to install tflite to run tvm. Existing method make sure that tflite package is needed only to parse lite models.

**Comment by FrozenGene** [comment]
@siju-samuel is correct. If we do like this pr, when we `import tvm`, the users will be required to install tflite package, which is not we want to see.

**Comment by u99127** [comment]
> 
> 
> @siju-samuel is correct. If we do like this pr, when we `import tvm`, the users will be required to install tflite package, which is not we want to see.

I missed that when I did the PR and now notice this to be the case in all the frontends, so I'll fix that.

I take it also that it is desirable to reduce the duplication and it should be possible to find another suitable location within the same file. The number of imports now reduces from about 120 to 53.

**Comment by u99127** [comment]
> > @siju-samuel is correct. If we do like this pr, when we `import tvm`, the users will be required to install tflite package, which is not we want to see.
> 
> I missed that when I did the PR and now notice this to be the case in all the frontends, so I'll fix that.
> 
> I take it also that it is desirable to reduce the duplication and it should be possible to find another suitable location within the same file. The number of imports now reduces from about 120 to 53.

Now only restricted to tflite.Operator, please help review and merge .

Ramana

**Comment by FrozenGene** [comment]
@siju-samuel could you help to review it again?

**Comment by FrozenGene** [comment]
Thanks @u99127 @u99127 !

**Pull request merged**
