### PR TITLE
[Autotvm] Fix autotvm customized template

### PR DESCRIPTION
**Pull request by icemelon9**
Fix the issue that autotvm customized template cannot get the config from dispatcher.

see details: https://discuss.tvm.ai/t/autotvm-error-in-the-conv2d-auto-tuning-tutorial-cannot-find-config-for-target-cuda-workload-none-etc/5919

### CODE REVIEW

**Comment by icemelon9** [comment]
cc @comaniac @merrymercy @ZihengJiang

**Comment by icemelon9** [comment]
@comaniac Yes, I think `_regsiter_task_compute`, `_regsiter_task_schedule`, `_regsiter_customized_template` should not be user facing APIs. We should use `register_topi_compute`, `register_topi_schedule`, `template` instead.

**Comment by comaniac** [comment]
> @comaniac Yes, I think `_regsiter_task_compute`, `_regsiter_task_schedule`, `_regsiter_customized_template` should not be user facing APIs. We should use `register_topi_compute`, `register_topi_schedule`, `template` instead.

I see. Make sense to me.

**Comment by kevinthesun** [comment]
Thanks @icemelon9 @comaniac

**Pull request merged**
