### PR TITLE
Improve reduction schedule on arm CPUs

### PR DESCRIPTION
**Pull request by giuseros**
This improves reduction by ~10x using x86 schedules. While for `float32` reduction is not common, it is widely used in quantized operations (`int8`, `uint8`) in order to compute the offset contributions. 

We might revisit this later to tailor the schedule for Arm CPUs. 

Change-Id: I9cd85deac6a57666b82ff7250d827652a4000d82

### CODE REVIEW

**Comment by giuseros** [comment]
cc @u99127 @anijain2305

**Comment by anijain2305** [comment]
Can you please retrigger the CI. It is failing due to a known issue - https://github.com/apache/incubator-tvm/pull/6084

**Comment by giuseros** [comment]
Hi @anijain2305 ,

Thanks for the approval! I did as you said and re-triggered the CI

**Comment by anijain2305** [comment]
Thanks @giuseros This is merged!

**Pull request merged**
