### PR TITLE
[VTA] quant support for alu-only op

### PR DESCRIPTION
**Pull request by zhanghaohit**
This is related to #5840 and split from PR #6126

This PR is to support ALU-only op to be a standalone fused op, which can be run on VTA.

### CODE REVIEW

**Comment by u99127** [comment]
Gentle request to put something like [VTA] in your subject line so that a git log shows a useful message.

**Comment by zhanghaohit** [comment]
ping @tmoreau89

**Review by tmoreau89 — APPROVED** [review]
Thanks @zhanghaohit the PR looks good to me

**Comment by tqchen** [comment]
@zhanghaohit please rebase and we can merge

**Comment by zhanghaohit** [comment]
> @zhanghaohit please rebase and we can merge

Done. Thanks @tqchen for the reminder.

**Comment by tqchen** [comment]
THanks @zhanghaohit @tmoreau89 @u99127 !

**Pull request merged**
