### PR TITLE
Update search for bitcode files for rocm 3.9

### PR DESCRIPTION
**Pull request by t-vi**
rocm 3.9 moved the bitcodes, we adapt to that.
As this gives opaque error messages that are hard to debug (loading the module fails with could not initialize shared object but does not tell you about the missing symbols), we tighten the checks at this stage:
- we become more strict with missing bitcodes,
- we let the linker fail loudly for unresolved symbols.

@masahi

### CODE REVIEW

**Review by masahi — APPROVED** [review]

**Comment by t-vi** [comment]
I could use a hint regarding the CI failure.

**Comment by jroesch** [comment]
It looks like it could be flaky networking? networking code can be flaky even on localhost. I re-ran pipeline any thoughts @tqchen or @areusch

**Comment by areusch** [comment]
@jroesch @t-vi best guess is a race condition in the test--it launches an rpc.Server, doesn't wait for it to start listening, then immediately connects. you can see in the captured teardown stdio that the "listening" message is printed, so i'd guess the test could use like a sleep(0.1) or better yet a retry on the connect call.

**Comment by masahi** [comment]
Thanks @t-vi

**Comment by t-vi** [comment]
Thank you @masahi and @jroesch and @areusch!

**Pull request merged**
