### PR TITLE
[Relay][Pass] Fix bug in re-processing call node in MergeComposite pass

### PR DESCRIPTION
**Pull request by soiferj**
This fixes a bug where call nodes are recursively processed more than once, potentially resulting in a composite function containing duplicate nodes. This change introduces a `call_map`, similar to the `var_map`, to keep track of call nodes that we've processed.

I found this bug while writing a pattern for a single-layer transformer.

@mbarrett97 @comaniac would you be able to take a look?

### CODE REVIEW

**Comment by soiferj** [comment]
Sure, I'll work on adding a unit test.

**Comment by mbarrett97** [comment]
Good catch :) Fix looks to be correct, looking forward to the test case.

**Comment by soiferj** [comment]
@mbarrett97 @comaniac I just pushed a test where "result" creates an incorrect graph, and "expected" is correct. Even those these two graphs are different, and "result" generated an incorrect function, they are computationally equivalent. This means that the test actually passes `alpha_equal` both with and without the bug. Here are the Relay outputs. The pattern I am trying to match is `add -> add -> add`.

Result:
```
v0.0.4
fn (%a: Tensor[(10, 10), float32], %b: Tensor[(10, 10), float32]) -> Tensor[(10, 10), float32] {
  %0 = subtract(%a, %b) /* ty=Tensor[(10, 10), float32] */;
  %4 = fn (%x: Tensor[(10, 10), float32], %y: Tensor[(10, 10), float32], Primitive=1, Composite="add_add_add") -> Tensor[(10, 10), float32] {
    %1 = add(%x, %y) /* ty=Tensor[(10, 10), float32] */;
    %2 = add(%x, %1) /* ty=Tensor[(10, 10), float32] */;
    %3 = add(%x, %y) /* ty=Tensor[(10, 10), float32] */;
    add(%2, %3) /* ty=Tensor[(10, 10), float32] */
  };
  %4(%0, %b) /* ty=Tensor[(10, 10), float32] */
}
```

Expected:
```
v0.0.4
fn (%a: Tensor[(10, 10), float32], %b: Tensor[(10, 10), float32]) -> Tensor[(10, 10), float32] {
  %0 = subtract(%a, %b) /* ty=Tensor[(10, 10), float32] */;
  %3 = fn (%in_1: Tensor[(10, 10), float32], %in_2: Tensor[(10, 10), float32]) -> Tensor[(10, 10), float32] {
    %1 = add(%in_1, %in_2) /* ty=Tensor[(10, 10), float32] */;
    %2 = add(%in_1, %1) /* ty=Tensor[(10, 10), float32] */;
    add(%2, %1) /* ty=Tensor[(10, 10), float32] */
  };
  %3(%0, %b) /* ty=Tensor[(10, 10), float32] */
}
```

**Comment by zhiics** [comment]
@soiferj Sorry. I don't quite understand the problem. Do you mean that these two expressions can pass alpha_equal check?

**Comment by soiferj** [comment]
Yes, they both pass the alpha_equal check.

**Comment by zhiics** [comment]
@soiferj hmm, this looks a bit wired to me, I will take a look at it. Thanks.

**Comment by mbarrett97** [comment]
You could try graph_equal which claims to check for data flow equivalency, although I am a bit surprised alpha_equal doesn't catch this. Failing that, maybe a static traversal is another option.

**Comment by soiferj** [comment]
graph_equal also succeeds on the buggy graph :( @zhiics, let me know when you have any findings!

**Comment by mbarrett97** [comment]
Unless I'm missing something, those graphs don't appear to me to be 'data flow equivalent', so this may be a bug with graph_equal.

**Comment by soiferj** [comment]
I'll do some investigation :)

**Comment by zhiics** [comment]
graph equal would not make a difference here as it checks free vars. I might not have time today. I can spend some time on it over the weekend.

**Comment by zhiics** [comment]
hmm, I just tried this:

```python
def test():
    tt = relay.TensorType([10, 10], "float32")
    a = relay.Var("a", tt)
    b = relay.Var("b", tt)
    sub = relay.subtract(a, b)

    x = relay.Var("x", tt)
    y = relay.Var("y", tt)

    add1 = x + y
    add2 = x + add1
    add3 = x + y
    add4 = add2 + add3

    fn = relay.Function([x, y], add4)
    fn = fn.set_attribute("Primitive", tvm.tir.IntImm("int32", 1))
    fn = fn.set_attribute("Composite", tvm.tir.StringImm("add_add_add"))
    fn_call = relay.Call(fn, [sub, b])

    func = relay.Function([a, b], fn_call)
    func = run_opt_pass(func, relay.transform.InferType())
    print(func)

    tt0 = relay.TensorType([10, 10], "float32")
    a0 = relay.Var("a0", tt0)
    b0 = relay.Var("b0", tt0)
    sub0 = relay.subtract(a0, b0)

    x0 = relay.Var("x0", tt0)
    y0 = relay.Var("y0", tt0)

    add01 = x0 + y0
    add02 = x0 + add01
    add03 = add02 + add01

    fn0 = relay.Function([x0, y0], add03)
    fn_call0 = relay.Call(fn0, [sub0, b0])
    func0 = relay.Function([a0, b0], fn_call0)
    func0 = run_opt_pass(func0, relay.transform.InferType())

    print(func0)
    assert alpha_equal(func, func0)
```
It could not pass alpha_equal. Are we missing something here? Can you double check if the program I provided are identical yours here?

**Comment by soiferj** [comment]
That's really strange - it looks right. Are you able to pull my branch and give the test a try?

**Comment by zhiics** [comment]
I can give it a try over the weekend, but why do you feed the expected with an unexpected expression?

**Comment by soiferj** [comment]
Sorry, what exactly do you mean?

**Comment by zhiics** [comment]
I though you provided
```
v0.0.4
fn (%a: Tensor[(10, 10), float32], %b: Tensor[(10, 10), float32]) -> Tensor[(10, 10), float32] {
  %0 = subtract(%a, %b) /* ty=Tensor[(10, 10), float32] */;
  %3 = fn (%in_1: Tensor[(10, 10), float32], %in_2: Tensor[(10, 10), float32]) -> Tensor[(10, 10), float32] {
    %1 = add(%in_1, %in_2) /* ty=Tensor[(10, 10), float32] */;
    %2 = add(%in_1, %1) /* ty=Tensor[(10, 10), float32] */;
    add(%2, %1) /* ty=Tensor[(10, 10), float32] */
  };
  %3(%0, %b) /* ty=Tensor[(10, 10), float32] */
}
```
as expected, instead of,

```
v0.0.4
fn (%a: Tensor[(10, 10), float32], %b: Tensor[(10, 10), float32]) -> Tensor[(10, 10), float32] {
  %0 = subtract(%a, %b) /* ty=Tensor[(10, 10), float32] */;
  %4 = fn (%x: Tensor[(10, 10), float32], %y: Tensor[(10, 10), float32], Primitive=1, Composite="add_add_add") -> Tensor[(10, 10), float32] {
    %1 = add(%x, %y) /* ty=Tensor[(10, 10), float32] */;
    %2 = add(%x, %1) /* ty=Tensor[(10, 10), float32] */;
    %3 = add(%x, %y) /* ty=Tensor[(10, 10), float32] */;
    add(%2, %3) /* ty=Tensor[(10, 10), float32] */
  };
  %4(%0, %b) /* ty=Tensor[(10, 10), float32] */
}
```

I just double checked. You are actually providing the latter as expected which is good. The mentioned bug (if it is) is actually a separate issue that doesn't block this PR. So we are good for this PR, right?

**Comment by soiferj** [comment]
I think so. If everyone else is okay, I think it's best to check this fix in.

**Comment by mbarrett97** [comment]
So is the issue that the test case currently passes both pre and post fix? If so, I'd say it probably does block the PR. We need to understand whether alpha_equal is an acceptable way to test equality here and if it's not, use an alternative method.

**Comment by soiferj** [comment]
Actually, are you sure the second argument is expected? It looks like AlphaEqual loops through the LHS args. This has some weird implications, when I run the other tests and flip the order of `result` and `expected` in alpha_equal, they fail.

Maybe this is because the "expected" doesn't have the composite and primitive attributes?

**Comment by soiferj** [comment]
If I flip the arguments to alpha_equals and properly add the attributes to the "expected" function, the tests work as expected. With everyone's okay, can I go ahead with this change?

**Comment by zhiics** [comment]
I am okay with it as the failure should be separate issue from `alpha_equal`. But I would suggest we create minimal example to reproduce the bug and open an issue for it so that ppl can conveniently look into it.

**Comment by mbarrett97** [comment]
So long as the test now correctly fails for the current behaviour, I'm happy. The ordering mattering is a concern for all the other tests though which have 'expected' as the second argument.

**Comment by soiferj** [comment]
This is actually a good exercise, as some other tests are actually failing now due to the graphs not being the same. For example, `test_branch_merge`. @mbarrett97, I'll push the changes, let me know what you think.

**Comment by soiferj** [comment]
Thanks everyone for working through this with me!

**Comment by zhiics** [comment]
@soiferj Can you also try to create a minimal example? Thanks.

**Comment by soiferj** [comment]
Definitely, I'll do that after fixing this.

**Comment by soiferj** [comment]
This test is now failing at the de-duplicate pass. It's interesting since the "correct" graph has the exact same function duplicated twice. Whereas the "expected" graph is just re-using the same function. What should be the correct behavior?

**Comment by soiferj** [comment]
Alright, sorry for all of the spam. All tests are now fixed. cc @zhiics @mbarrett97

**Comment by zhiics** [comment]
Thanks for the effort. I will take a look later. So, do we still need to flip the args? If so, we still need to create a repo and open an issue.

**Comment by soiferj** [comment]
It seems like we need to flip the args. I’ll open the issue on Monday.

**Comment by soiferj** [comment]
@zhiics I merged your changes and updated the branch. Would you mind taking another look?

**Comment by zhiics** [comment]
@mbaret PTAL. Let's land this if it looks good to you as well.

**Comment by mbaret** [comment]
Looks good.

**Comment by zhiics** [comment]
Thanks @soiferj @mbaret @cbalint13

**Pull request merged**
