### PR TITLE
[VTA][Chisel] Change Scala Linter scalafmt => scalastyle

### PR DESCRIPTION
**Pull request by liangfu**
As scalafmt changes the code even with `--test` argument in the latest version, this PR switches scala linter for Chisel VTA from scalafmt to scalastyle.

@tmoreau89 @vegaluisjose Please review.

### CODE REVIEW

**Comment by liangfu** [comment]
vta/apps still need to be updated.

**Comment by tmoreau89** [comment]
Thanks @liangfu ; let us know when it's ready for a merge.

**Comment by liangfu** [comment]
@tmoreau89 @vegaluisjose Thanks for the review. I think this is now ready for a merge, and let's wait for the CI testing results.

**Comment by liangfu** [comment]
In addition, I made some final changes in fixing indentation errors, here is a typical example:
```diff
diff --git a/vta/hardware/chisel/src/main/scala/core/Load.scala b/vta/hardware/chisel/src/main/scala/core/Load.scala
index 7c79498bd..50c26bb8e 100644
--- a/vta/hardware/chisel/src/main/scala/core/Load.scala
+++ b/vta/hardware/chisel/src/main/scala/core/Load.scala
@@ -25,12 +25,12 @@ import vta.util.config._
 import vta.shell._
 
 /** Load.
-  *
-  * Load inputs and weights from memory (DRAM) into scratchpads (SRAMs).
-  * This module instantiate the TensorLoad unit which is in charge of
-  * loading 1D and 2D tensors to scratchpads, so it can be used by
-  * other modules such as Compute.
-  */
+ *
+ * Load inputs and weights from memory (DRAM) into scratchpads (SRAMs).
+ * This module instantiate the TensorLoad unit which is in charge of
+ * loading 1D and 2D tensors to scratchpads, so it can be used by
+ * other modules such as Compute.
+ */
 class Load(debug: Boolean = false)(implicit p: Parameters) extends Module {
   val mp = p(ShellKey).memParams
   val io = IO(new Bundle {
@@ -110,11 +110,10 @@ class Load(debug: Boolean = false)(implicit p: Parameters) extends Module {
       when(dec.io.isSync) {
         printf("[Load] start sync\n")
       }.elsewhen(dec.io.isInput) {
-          printf("[Load] start input\n")
-        }
-        .elsewhen(dec.io.isWeight) {
-          printf("[Load] start weight\n")
-        }
+        printf("[Load] start input\n")
+      }.elsewhen(dec.io.isWeight) {
+        printf("[Load] start weight\n")
+      }
     }
     // done
     when(state === sSync) {
```
Please take another look.

**Comment by tmoreau89** [comment]
Thanks for the diff @liangfu ; this looks great.

**Comment by tmoreau89** [comment]
Looks like CI failed on one of the unit tests

**Comment by liangfu** [comment]
I think it might related to #4901 , let me trigger the testing pipeline again.

**Comment by tmoreau89** [comment]
Thanks @liangfu, @vegaluisjose the PR has been merged!

**Pull request merged**
