### PR TITLE
[VTA][Runtime] fix hardcoded VerifyDep step

### PR DESCRIPTION
**Pull request by zhanghaohit**
Bug Description
----
VerifyDep hardcode step check of 2, which is not true in other dependence settings (e.g., if we change the acc dependence distance in VTA hardware implementation)

Solution
----
add `ACC_DEP_DISTANCE` in vta_config.json and use that to derive checking `step`.

`ACC_DEP_DISTANCE` is also used in VTA hardware implementation when defining acc dependence distance (see [here](https://github.com/apache/incubator-tvm-vta/pull/8))

### CODE REVIEW

**Comment by zhanghaohit** [comment]
@tqchen @tmoreau89 Could you kindly help review this PR? Thanks.

**Comment by zhanghaohit** [comment]
> Thanks @zhanghaohit for the proposed change, moving away from a hardcoded value is the right move!
> 
> I find the `ACC_DEP_DISTANCE` to be confusing however. Ultimately it's derived from the latency (in cycles) it takes for a write to address `X` to be visible on the read port at address `X`. Maybe we can dub this `SRAM_WRITE_TO_READ_LATENCY` or something along those lines?

Thanks @tmoreau89 for the suggestion. I think `VerifyDep` here is to [`verify that we don't write to the same acc_mem index two cycles in a row`](https://github.com/apache/incubator-tvm/blob/684f2d7b89e29b92cdac5389df58ba5a70782c2a/vta/runtime/runtime.cc#L289) (I may also need to change the comments).

The `ACC_DEP_DISTANCE` is the same as [here](https://github.com/apache/incubator-tvm-vta/pull/8). Did I get the correct meaning of [`VerifyDep`](https://github.com/apache/incubator-tvm/blob/684f2d7b89e29b92cdac5389df58ba5a70782c2a/vta/runtime/runtime.cc#L290)?

**Comment by tqchen** [comment]
ping @tmoreau89 @zhanghaohit  please followup :)

**Comment by zhanghaohit** [comment]
> ping @tmoreau89 @zhanghaohit please followup :)

Thanks @tqchen for the reminder. I think this PR depends on this [PR](https://github.com/apache/incubator-tvm-vta/pull/8) in VTA repo. 
@tmoreau89 could you kindly review and input your suggestions? Thanks.

**Pull request closed without merging**
