### PR TITLE
[DOCS] Fix Sphinx Warning: the target found for cross-reference

### PR DESCRIPTION
**Pull request by cchung100m**
Hi @tqchen @comaniac 

Following issue #4908 and our discussion, this PR is going to fix the following two errors

```
WARNING: 'any' reference target not found: 
WARNING: Unknown target name: 
```

I would appreciate that if you could help to review/manage it, thanks.

### CODE REVIEW

**Comment by comaniac** [comment]
The log shows 25 warnings including 4 undefined labels. Could you take a look and fix them? Other major warnings are related to lex python. You can also try to fix it, or I’ll take a look next week.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by cchung100m** [comment]
Hi @comaniac 

Thanks for the review.

I solve the undefined label warnings and the output file as shown below link:

https://gist.github.com/cchung100m/f8bdef470b1a41c2408895610ee3b03e

**Comment by cchung100m** [comment]
@tqchen @comaniac 

Thanks for the review and feedback. :)

**Comment by tqchen** [comment]
Thansk @comaniac @cchung100m

**Pull request merged**
