### PR TITLE
[CI][Docker] pin xgboost dependency version to 0.90

### PR DESCRIPTION
**Pull request by leandron**
Pin xgboost dependency version to 0.90

 * Sets xgboost dependency to be 0.90, preventing
   segfaults during TVM python unit tests execution

 * This is discussed in issue #4953

cc @tqchen

### CODE REVIEW

**Comment by leandron** [comment]
It seems the broken build reason is not specifically related to this patch.

**Comment by masahi** [comment]
hey @leandron we are in the same boat. The discussion is happening at https://github.com/apache/incubator-tvm/pull/4961#issuecomment-592299187

**Comment by leandron** [comment]
> hey @leandron we are in the same boat. The discussion is happening at [#4961 (comment)](https://github.com/apache/incubator-tvm/pull/4961#issuecomment-592299187)

Thanks @masahi, I posted my comments there.

**Comment by tqchen** [comment]
the fix has been merged, please send another commit to retrigger the CI

**Comment by tqchen** [comment]
Reopen won't trigger the case, need a dummy commit

**Comment by cchung100m** [comment]
@leandron 

Please use the command below to submit a dummy commit, thanks.

`git commit --allow-empty -m "Trigger CI"`

**Comment by masahi** [comment]
no need to do dummy commit, just fetch and rebase against master

**Comment by leandron** [comment]
Thanks @masahi @cchung100m @tqchen

**Comment by tqchen** [comment]
Thanks @leandron this is merged.

it would be great if you and @hcho3 can followup on https://github.com/apache/incubator-tvm/issues/4953 given that we have quite a bit of overlap between the two communities, we want to make sure the latest XGBoost and TVM works together

**Comment by leandron** [comment]
Thanks @tqchen. I'll see to provide @hcho3 with instruction on how to reproduce the issue I see on xgboost.

**Pull request merged**
