### PR TITLE
[TOPI][CUDA] Teak CUDA injective scheduler

### PR DESCRIPTION
**Pull request by wpan11nv**
- vectorizing fp32/int32 types is also beneficial.

Signed-off-by: Wei Pan <weip@nvidia.com>

Thanks for contributing to TVM!   Please refer to guideline https://docs.tvm.ai/contribute/ for useful information and tips. After the pull request is submitted, please request code reviews from [Reviewers](https://github.com/apache/incubator-tvm/blob/master/CONTRIBUTORS.md#reviewers) by @ them in the pull request thread.

### CODE REVIEW

**Comment by wpan11nv** [comment]
Perf data on 1080TI with n = 134217728

Exec time without vectorization: 3.923180 ms., float32
Exec time without vectorization: 3.922209 ms., int32
    
Exec time with vectorization: 3.076118 ms., float32
Exec time with vectorization: 3.078727 ms., int32

**Comment by jmorrill** [comment]
I applied this commit and I get the following exception when I "build_module" (On a 1080GTX):

```
tvm._ffi.base.TVMError: Traceback (most recent call last):
  File "C:\src\mediatubes\ml\tensortubes\src\third_party\tvm\src\target\source\codegen_cuda.cc", line 157
TVMError: Cannot convert type uint1x4 to CUDA type!
```

**Comment by wpan11nv** [comment]
> type!

What is your test? I'll have a look. Thanks!

**Comment by jmorrill** [comment]
> > type!
> 
> What is your test? I'll have a look. Thanks!
On a 1080gtx
Using [this mxnet model](http://insightface.ai/files/models/arcface_r100_v1.zip)
Using [this log](https://www.dropbox.com/s/o991q7r1hnuu9qw/resnet-arc-50-win.log?dl=0) from the latest autotvm.

And a similar python script
```
    with autotvm.apply_history_best(log_file):
        with relay.build_config(opt_level=3):
            graph, lib, params = relay.build_module.build(
                mod, target=target, params=params)
```

**Comment by wpan11nv** [comment]
@jmorrill Could you help review #4983 first? This PR exposed a bug in TVM codegen. #4983 fixed it. Thanks!

**Comment by jmorrill** [comment]
> @jmorrill Could you help review #4983 first? This PR exposed a bug in TVM codegen. #4983 fixed it. Thanks!

In addition to #4983, I applied this patch also and compiling & autotvm now happen w/o error.

**Comment by masahi** [comment]
Will take a look at this too

**Comment by masahi** [comment]
@wpan11nv #4983 was merged, please update this PR.

**Comment by tqchen** [comment]
ping @wpan11nv

**Comment by wpan11nv** [comment]
> ping @wpan11nv 

@tqchen there are still bugs exposed by vectorization. I'm working on something else right now, and I'll try to fix them asap.

**Comment by tqchen** [comment]
cc @wpan11nv can we followup on the status of this PR. thanks!

**Pull request closed without merging**
