### PR TITLE
update pyxir version to 0.1.3

### PR DESCRIPTION
**Pull request by shibuiwilliam**
Update PYXIR version from 0.1.2 to 0.1.3.

> Thanks for contributing to TVM!   Please refer to guideline https://tvm.apache.org/docs/contribute/ for useful information and tips. After the pull request is submitted, please request code reviews from [Reviewers](https://github.com/apache/incubator-tvm/blob/master/CONTRIBUTORS.md#reviewers) by @ them in the pull request thread.

### CODE REVIEW

**Review by leandron — COMMENTED** [review]
Hi @shibuiwilliam, thanks for the PR. Would you mind providing a bit more context on why this update is needed?

**Comment by leandron** [comment]
Just noticed that this PR also is duplicated with https://github.com/apache/incubator-tvm/pull/6716, maybe you need to organise with @anilmartha, to see which one we merge.

**Review by comaniac — APPROVED** [review]

**Comment by comaniac** [comment]
I merged this one since it has passed the CI. Thanks @shibuiwilliam @anilmartha @leandron

**Comment by shibuiwilliam** [comment]
Thanks!
This PR was to update PYXIR version to pass vitis ai installation.

**Pull request merged**
