### PR TITLE
[Runtime] Enable set_output in GraphRuntime

### PR DESCRIPTION
**Pull request by benjamim93**
set_output is enabled to redirect the output, with unnecessary copies saved. It can be regarded as the output version of set_input_zero_copy.

### CODE REVIEW

**Comment by benjamim93** [comment]
Review request @hlu1 @zhiics

**Comment by tqchen** [comment]
I am not sure if this version is necessary since it involves a lot of changes to the graph runtime itself. Given that zero copy in the output can be relatively rare, perhaps we want to leave it out for simplicity.

**Comment by hlu1** [comment]
I don't think you need to implement a non-copy version of set_output if you simply want to avoid copy. `GetOutput` returns a NDArray, which is essentially a shared_ptr to the underlying tensor:

https://github.com/apache/incubator-tvm/blob/master/src/runtime/graph/graph_runtime.cc#L156-L160

**Comment by tqchen** [comment]
close for now as per the reasons stated above Thanks @benjamim93 @hlu1

**Pull request closed without merging**
