### PR TITLE
Remove deprecated opengl files

### PR DESCRIPTION
**Pull request by tqchen**

### CODE REVIEW

**Comment by tqchen** [comment]
cc @icemelon9 @zhiics @yzhliu

**Comment by zhiics** [comment]
BTW, do we still need to keep the files under src/runtime/opengl ?

**Comment by icemelon9** [comment]
Do we still need the `type_hint` in the device API that is specific for opengl?

**Comment by tqchen** [comment]
@icemelon9 I think it makes sense to keep it since future graphics API like vulkan could benefit from it, if we decide to extend include texture memory support.

**Comment by tqchen** [comment]
@zhiics Good point, i opened https://github.com/apache/incubator-tvm/pull/5712 for that

**Pull request merged**
