### PR TITLE
Qnn quantize with min max using Mxnet flavor to support Mxnet prequantized models.

### PR DESCRIPTION
**Pull request by shoubhik**
- For quantization implementation rounding after addition to increase accuracy.
- Adding support for Mxnet flavored quantization for both default and using MKLDNN. User can choose between the two at runtime.
- Added tests for new methods added.

### CODE REVIEW

**Comment by shoubhik** [comment]
@yzhliu Can you please review this?

**Comment by wweic** [comment]
@yzhliu @icemelon9 @kevinthesun @zhiics hey, could someone take a look at the PR? It will help refine the implementation.

**Comment by zhiics** [comment]
@shoubhik @anijain2305  Please rebase it first. There are conflicts. I will find some slots by tomorrow to do a pass on it. Thanks.

**Comment by tqchen** [comment]
closue due to inactive status

**Pull request closed without merging**
