### PR TITLE
[BACKPORT-0.6][Bugfix][Arith] keep div_mode during floordiv simplify

### PR DESCRIPTION
**Pull request by yzhliu**
@tqchen @sergei-grechanik please take a look.

### CODE REVIEW

**Comment by tqchen** [comment]
Thanks @yzhliu , seems we need a different testcase, that uses a truncdiv but still triggers DivModeCompatibleTo

**Comment by ANSHUMAN87** [comment]
@yzhliu :  The issue is fixed indeed, Thanks!
 I think it would be good if we add the issue test case as well.

--> expr = (((x0 - floordiv((0 - (x1*5)), 2)) - 1) + floordiv((37 + ((x1 + 7)*-5)), 2))

**Comment by ANSHUMAN87** [comment]
@tqchen, @yzhliu : I have one concern here.
As you see the expr below:
expr = (((x0 - floordiv((0 - (x1*5)), 2)) - 1) + floordiv((37 + ((x1 + 7)*-5)), 2))

should be evaluated to actually
expr = x0

but with current simplify stage(rewrite_simplify + canonical_simplify), it evaluates to below:
expr = ((floordiv((0 - (x1: int32*5)), 2) + x0: int32) - floordiv((x1*-5), 2))

But when i run stages as (rewrite_simplify + canonical_simplify + rewrite_simplify) it evaluates perfectly to x0.

So may be we need to run these stages with some customized config every time or until there are no more changes?

**Comment by yzhliu** [comment]
@ANSHUMAN87 good catch, this is what the argument `step` for I added in #5618

**Comment by tqchen** [comment]
@yzhliu please also send a patch to v0.6

**Pull request merged**
