### PR TITLE
[VTA][Xilinx] Update to Vivado 2020.1 and Pynq 2.5

### PR DESCRIPTION
**Pull request by tmoreau89**
Summary:
* Bumping Vivado version to the lastest 2020.1 thanks to @vegaluisjose's PR https://github.com/apache/incubator-tvm-vta/pull/10
* Updating docs to reflect version change
* Update Pynq image to 2.5 (latest)
* Instructions to get a properly built and linked RPC server runtime which will need to be fixed in a subsequent PR

### CODE REVIEW

**Comment by tmoreau89** [comment]
@vegaluisjose @liangfu @huajsj

**Comment by vegaluisjose** [comment]
LGTM

**Review by vegaluisjose — APPROVED** [review]

**Review by liangfu — APPROVED** [review]
LGTM

**Comment by liangfu** [comment]
Thanks @tmoreau89 @vegaluisjose , this is now merged.

**Pull request merged**
