### PR TITLE
[CI][Docker] Bump ONNX version to 1.6

### PR DESCRIPTION
**Pull request by masahi**
This is a prerequisite for #4536 

cc @tqchen @jwfromm

### CODE REVIEW

**Comment by jwfromm** [comment]
Have you managed to get `onnx.checker.check_model` to work with ONNX 1.6? Whenever I've tried updating I encounter frequent segmentation faults. This is a known bug with 1.6 as seen in [this Onnx issue](https://github.com/onnx/onnx/issues/2394). Assuming it still is around, we either have to drop use of the model checker (which is probably fine since it's not essential) or wait until they fix it in 1.7. If you want to go with the former, you should include the removal of the checker with this PR.

**Comment by masahi** [comment]
With ONNX v1.6, I do get segfault when importing both ONNX and PyTorch (seems to be the same issue as [this one](https://github.com/onnx/onnx/issues/1331)). If I remove PyTorch import, my test case in #4536, which uses onnxruntime (which in tern calls check_model) works fine. The following works for me too.
```
import resnet
model = onnx.load("resnet50.onnx") 
onnx.checker.check_model(model)
```

Doesn't the CI = green mean we are good to go wiht v1.6? Assuming the CI is running on v1.6 with the in this PR.

**Comment by tqchen** [comment]
The CI is not directly updated when the docker get updated, see https://docs.tvm.ai/contribute/pull_request.html#ci-environment . Would be great if we can have tests to confirm things, i will also followup later this week.

**Comment by masahi** [comment]
Running tests/python/frontend/onnx/test_forward.py with the new CI should confirm whether ONNX v1.6 is in good state. Based on the discussion so far, it seems likely to crash.

**Comment by tqchen** [comment]
I will suggest we wait until onnxrt 1.7 then as per suggested by @jwfromm @masahi shall we close for now?

**Comment by masahi** [comment]
Ok, no problem for me.

**Comment by masahi** [comment]
I've tested on an environment with ONNX 1.6 + PyTorch master build, I can run onnx/test_forward.py without any issue. I recommend updating our CI env to PyTorch 1.4 (which should be out soon) along with ONNX 1.7.

**Pull request closed without merging**
