### PR TITLE
Switch CRC-CCITT libraries

### LINKED ISSUE #6496: [uTVM] Use an alternative CRC Library
The 3rdparty crc library introduced in https://github.com/apache/incubator-tvm/pull/6334 has a license problem.

We will need to replace it with a new impl or an alternative library

### PR DESCRIPTION
**Pull request by areusch**
Fixes #6496. 

I found an MIT-licensed library that was fairly easy to adapt, but I had to make some changes on top of the pristine import. I feel like we normally use submodule, but given changes were needed, imported with subtree and patched on top. let me know if you prefer a different approach.

### CODE REVIEW

**Comment by areusch** [comment]
cc @tqchen

**Review by tqchen — APPROVED** [review]

**Comment by tqchen** [comment]
@areusch the vta-hw update might be unintended, please use git submodule update to point to the upstream code

**Comment by areusch** [comment]
ugh, fixed

**Comment by cbalint13** [comment]
@areush, @tqchen 

Wouldn't be better to use boost's crc  ?
https://www.boost.org/doc/libs/1_74_0/doc/html/crc.html
https://stackoverflow.com/questions/36732949/boost-crc-16-bit

* We could only add boost detection to actual cmake flow and just use it.

**Review by cbalint13 — CHANGES_REQUESTED** [review]
See question in conversation thread.

**Comment by tqchen** [comment]
Thansk @cbalint13 I believe the main concern here is the need for a minimum C impl for micro controllers, so boost/llvm cannot be used in this case. Although the most ideal case might be a mininum impl in the uTVM source. I am going to merge this for now.

**Pull request merged**
