### PR TITLE
Dynamic gpu tests, add dynamic strided slice to topi

### PR DESCRIPTION
**Pull request by mbrookhart**
cc @zhiics 

Like I said, this is from my topk branch, which is still having issues with memory corruption, so I'm not actually using the topi version by this commit.

Let me know if this works for argwhere, I'll try to update it with a topi unit test this afternoon.

### CODE REVIEW

**Comment by zhiics** [comment]
@mbrookhart Thanks for the PR. I think this probably solves the problem if we invoke from Relay directly. But similarly to topk, argwhere also needs to invoke strided_slice in topi. I think we also need to have a dispatch in topi to invoke each dyn_strided_slice or strided_slice.

**Comment by mbrookhart** [comment]
Oops! I was missing part of it in this commit, let me extract it from the other branch

**Comment by mbrookhart** [comment]
added the python api and tests

**Review by zhiics — APPROVED** [review]

**Review by kevinthesun — APPROVED** [review]
LGTM.

**Comment by kevinthesun** [comment]
Thanks! @mbrookhart @zhiics

**Pull request merged**
