### PR TITLE
[Quantization] Support for more ops (conv1d)

### PR DESCRIPTION
**Pull request by tmoreau89**
Quantization support for conv1d for custom model. Added additional ops to increase size of quantized subgraphs.

### CODE REVIEW

**Comment by tmoreau89** [comment]
@ZihengJiang I want to add more coverage for the quantizer, do we generally add unit tests when adding more ops or is this PR sufficient?

**Comment by ZihengJiang** [comment]
@tmoreau89 It is ok if you have verified that this PR doesn't affect the accuracy of common quantized models

**Comment by tmoreau89** [comment]
I did a spot check on a model that we're quantizing. Also ran some validation over a CIFAR-10 model from MxNet.

I'll change it to a PR for review.

**Comment by tmoreau89** [comment]
thanks @ZihengJiang @vinx13 PTAL!

**Review by ZihengJiang — APPROVED** [review]

**Review by liangfu — APPROVED** [review]

**Review by vinx13 — APPROVED** [review]

**Pull request merged**
