### PR TITLE
[TIR][REFACTOR] Remove ir_pass in favor of analysis/transform.

### PR DESCRIPTION
**Pull request by tqchen**
This PR removes ir_pass(old style pass functions) in favor
of analysis/transform(new style pass manager).

### CODE REVIEW

**Comment by tqchen** [comment]
The only TDB is hoist_if which will be carried by @kevinthesun 
cc @ZihengJiang @zhiics @yzhliu @icemelon9

**Comment by zhiics** [comment]
QQ: we will port BuildConfig to PassContext next?

**Comment by tqchen** [comment]
@zhiics Yes we will need to port BuildConfig->PassContext, though we might need to put some thoughts into how to organize these attributes (perhaps worth some an RFC if we have some ideas)

**Comment by wpan11nv** [comment]
The following line is broken after this change:

https://github.com/apache/incubator-tvm/blob/master/python/tvm/driver/build_module.py#L161

**Comment by tqchen** [comment]
Good catch, dump_ir is temporary disabled because we can move to the new PassContext trace API. We should remove that line, @wpan11nv can you send a patch?

**Pull request merged**
