### PR TITLE
add rocm schedules to topi C++

### PR DESCRIPTION
**Pull request by t-vi**
This imports the CUDA schedules to rocm.

@masahi

### CODE REVIEW

**Comment by petrex** [comment]
A good start. Next, we would like to differentiate AMD GPUs from Nvidia ones

**Comment by masahi** [comment]
@petrex you can approve it if you like :)

**Comment by petrex** [comment]
master @masahi : I'd love to help in the review but we need your approval and support!

**Comment by masahi** [comment]
Yeah I will review later today

**Pull request merged**
