### PR TITLE
[1] Test case modified for int type

### PR DESCRIPTION
**Pull request by ANSHUMAN87**
Thanks for contributing to TVM!   Please refer to guideline https://docs.tvm.ai/contribute/ for useful information and tips. After the pull request is submitted, please request code reviews from [Reviewers](https://github.com/apache/incubator-tvm/blob/master/CONTRIBUTORS.md#reviewers) by @ them in the pull request thread.

### CODE REVIEW

**Comment by ANSHUMAN87** [comment]
@tqchen , @MarisaKirisame, @zhiics

**Comment by tqchen** [comment]
Please look into the CI error

**Comment by ANSHUMAN87** [comment]
> Please look into the CI error

@tqchen : This error does not reproduce in my setup. Looks like some random issue. To isolate i may push some test commits, please ignore them. Thanks!

**Comment by ANSHUMAN87** [comment]
@tqchen : I am getting build error now in CI, does not look like related to my changes. It is in /tests/scripts/task_rust.sh. May be i will wait for that to get resolved? Please help. Thanks!

**Comment by tqchen** [comment]
The build error should have been fixed by a recent PR, please send a dummy commit to retrigger the CI

**Comment by ANSHUMAN87** [comment]
@tqchen , @MarisaKirisame : I found the root-cause for the CI failure. The reason is the legacy bit-shift operator overflow issue. As the second parameter was higher than 32(bit length of int32), the values produced by tvm operator becomes undefined. However i found numpy behavior is quite stable in this scenario. My personal opinion is to make the behavior inline with numpy. 

Currently in test case i have restricted the second parameter for left_shift and right_shift operator to be in range : [1, 31].
Please review and provide your valuable feedback. Thanks!

**Comment by tqchen** [comment]
Thanks @ANSHUMAN87 @MarisaKirisame !

**Pull request merged**
