### PR TITLE
[Topi, x86] Using MKL blas for quantized dense

### PR DESCRIPTION
**Pull request by anijain2305**
Using MKL for quantized dense, following the MKL fallback for FP32 dense.

On C5.12x large cascade lake with VNNI support, results for BERT base are as follows (latency in ms)

Type | Sequence length | MXNet+MKLDNN | TVM Alone  | TVM+MKL
-- | -- | -- | -- | --
FP32 | 128 | 33.56 | N/A | 16.83
Quantized | 128 | 23.94697 | 77.16 | 11.36

@icemelon9 @eric-haibin-lin @shoubhik 

TVM Alone has bad performance because we don't have a good integer dense schedule.

### CODE REVIEW

**Comment by anijain2305** [comment]
@eric-haibin-lin Yes, the MXNet+MKLDNN baseline is also in `int8`.

**Comment by TaoLv** [comment]
Better to show the performance of TVM before using MKL s8u8s32 GEMM.

**Comment by anijain2305** [comment]
@TaoLv Good point, I added the latency numbers for TVM alone. Thanks for pointing it out!

**Comment by anijain2305** [comment]
@icemelon9 Can you please manage this PR?

**Comment by anijain2305** [comment]
Ping @icemelon9

**Comment by tqchen** [comment]
While it is OK to make use of the mkldnn in this case, we should always work hard to get good integer schedules and learn from the insights, just as the case we did for the CUDA softmax and other cases.

**Comment by anijain2305** [comment]
@tqchen Agreed. For now, my reasoning was to just extend MKL to int8. But I agree that it will be better to focus on TVM schedules. This one will require more work as even FP32 schedules for dense are not well optimized.

**Comment by icemelon9** [comment]
Thanks @anijain2305 @eric-haibin-lin @TaoLv @tqchen

**Pull request merged**
