### PR TITLE
[Codegen] fix bug on LLVM 10.0

### PR DESCRIPTION
**Pull request by qingyunqu**
Thanks for contributing to TVM!   Please refer to guideline https://docs.tvm.ai/contribute/ for useful information and tips. After the pull request is submitted, please request code reviews from [Reviewers](https://github.com/apache/incubator-tvm/blob/master/CONTRIBUTORS.md#reviewers) by @ them in the pull request thread.

Fix `llvm::CGFT_xxx` to `llvm::TargetMachine::CGFT_xxx`.

### CODE REVIEW

**Comment by qingyunqu** [comment]
@yzhliu

**Comment by tqchen** [comment]
Thanks @qingyunqu !

**Comment by masahi** [comment]
@qingyunqu this breaks the build with the trunk as pointed out in #4386. Can you revert this change and instead fix version ifdef? Sorry I didnt test in llvm 10.0.

**Comment by qingyunqu** [comment]
@masahi Could I push a new version that reduce the second and the third ifdef into one?

**Comment by masahi** [comment]
No, second elif should be TVM_LLVM_VERSION <= 100. The last one is for the latest llvm.

**Comment by masahi** [comment]
@qingyunqu where did your get your llvm 10.0? It is not released yet

**Comment by qingyunqu** [comment]
@masahi Maybe I used the master branch of LLVM
截屏2019-12-10下午7 32 04

**Comment by masahi** [comment]
Ok, that means you are using an out of date LLVM trunk. Please send another PR that reverts this change. If you update and rebuild your LLVM, the build should succeed.

**Comment by qingyunqu** [comment]
@masahi Thanks, I will send the PR immediately.

**Comment by qingyunqu** [comment]
@masahi I have used svn to update my LLVM. But after rebuilding LLVM, the build of tvm without `TargetMachine::` also failed. May I make a mistake or misunderstand?

**Comment by masahi** [comment]
A couple of points:
* LLVM project moved to github https://github.com/llvm/llvm-project. You might want to switch to this repo from svn.
* Make sure you have the enum CodeGenFileType in [include/llvm/Support/Codegen.h](https://github.com/llvm/llvm-project/blob/master/llvm/include/llvm/Support/CodeGen.h#L63-L67) (not in TargetMachine.h)
* Make sure you are building TVM with the correct LLVM installation.

**Comment by qingyunqu** [comment]
Thanks, I have got the latest LLVM of `10.0.0git` version and found the enum CodeGenFileType. I will test the compilation on this version and then push another PR. Thanks a lot!

**Comment by qingyunqu** [comment]
@masahi I have compiled tvm with `10.0.0git` LLVM. There is something wrong when I run `cmake`:

截屏2019-12-12上午12 50 58

Then I comment the error line in `FindLLVM.cmake:43`. Everything becomes ok:

截屏2019-12-12上午12 55 11


Maybe there is better method to fix this?

**Comment by masahi** [comment]
I also remember seeing that error (but I don't remember how I fixed it). Unless you have a good solution for this, we can fix that later. If you've confirmed that you can build TVM with the LLVM trunk, please send a PR that reverts this change.

**Pull request merged**
