### PR TITLE
Early checking added and new test cases added for schedule fuse

### PR DESCRIPTION
**Pull request by ANSHUMAN87**
PR contains
1:> Early checking for inner & outer position orderings.
2:> New test case for the split+fuse and failure scenarios with reordering added.

### CODE REVIEW

**Comment by ANSHUMAN87** [comment]
@tqchen , @MarisaKirisame, @zhiics

**Comment by zhiics** [comment]
Could you add some description about what problems are trying to solve? It would help people to understand the purpose of the PR.

**Comment by ANSHUMAN87** [comment]
> Could you add some description about what problems are trying to solve? It would help people to understand the purpose of the PR.

@zhiics : Thanks for your feedback! It is done now!

**Comment by zhiics** [comment]
Thanks @ANSHUMAN87

**Pull request merged**
