### PR TITLE
[TEST] Various CI fixes for the VTA and Relay 

### PR DESCRIPTION
**Pull request by tqchen**
cc @tmoreau89 @dpankratz 

related https://github.com/apache/incubator-tvm/pull/5156

### CODE REVIEW

**Comment by tqchen** [comment]
cc @comaniac @zhiics I temporarily disabled the test check tests/python/relay/test_annotate_target.py:160 dnnl to recover the CI

Printing out the IR shows that the two IRs has slight difference in terms of the CompilerAttrs they use, given that the testcase passes before we merge https://github.com/apache/incubator-tvm/pull/5134 by @mbaret it might due to a regression introduced by that PR

**Comment by zhiics** [comment]
@tqchen Sure. We can send a fix because it was not rebased against the master where alpha_equal was removed now.

**Comment by tqchen** [comment]
Yes, we intentionally allow concurrent merge to reduce the CI burden(think it as a optimistic concurrent control in DB), and so far we have been quite good a fixing the immediate problems that arises.

**Comment by zhiics** [comment]
Great! We had this rebasing problem many times now. 

@mbaret please enable the test and send it together with the other fix your are working on.

**Comment by comaniac** [comment]
I was about to send a small PR for this but thanks for the quick fix.
@mbaret will send a follow-up PR to fix some issues including this unit test.

**Pull request merged**
