### PR TITLE
Some Windows and MSVC fixes

### PR DESCRIPTION
**Pull request by kice**
ref: https://github.com/apache/incubator-tvm/issues/4529

### CODE REVIEW

**Comment by kice** [comment]
looks like VS2019 output utf-8 now...XD

But old versions should still use local encoding.

**Comment by tqchen** [comment]
Can we run a test and set the function once for all? instead of doing the try catch inside every py_str call(which will be slow)?

**Comment by kice** [comment]
I think we should keep it since it is not perforamce critical and different programs might use different encoding on windows.

**Comment by tqchen** [comment]
Sorry I wasn't being clear, I agree that it is important to keep it, however, it might be better to implement it as follows(so condition is only executed once), I don't know if it is possible though

```python
if test_encode_utf9():
    py_str = lambda x: x.decode("utf-8")
else:
    py_str = lambda x: x.decode(oldencoding)

```

**Comment by kice** [comment]
I assume that everytime the byte array we feed `py_str` comes from different program, which might have different encoding.

The most common encoding just happend to be `utf-8` and defalut local system encoding.

For an uncommon situation, a program compiled under Japanese Windows and being executed on Chinese Windows might not display correctly, if it uses non-ascii (e.g. Chinese or Japanese) character. 
In addition, for this case, the codec retrieved from `GetACP()`, which is  Chinese default encoding ( or `GBK`) cannot decode the string (encoded by `Shift-JIS`) either. The only thing we can do is to test what encoding it uses ~or ask the author to recompile the program with utf-8~.

**Comment by tqchen** [comment]
OK this is merged. Thanks @kice

**Pull request merged**
