### PR TITLE
[CI] Tensorflow version support upgrade from 2.1.0 to 2.3.1

### PR DESCRIPTION
**Pull request by ANSHUMAN87**
Change summary:

- Version bumped latest up-to-date
- Few dependent failures resolved.

Background:
  Please refer #6685 .
To support recent advances in Sparse area in Tensorflow community, the version need to be upgraded.

cc @siju-samuel , @tkonolige , @tqchen , @jroesch , @junrushao1994 , @FrozenGene !

### CODE REVIEW

**Comment by ANSHUMAN87** [comment]
> Does this mean that users with tensorflow version <2.3.0 will not be able to import their models?

I am not too sure if i understood your query clearly. Please let me know in case my response is upto. 
If user has tensorflow version <2.3.0 , they might get error while executing our test scripts, but importing models if it is based on older version they should be able to do it.Thanks!

**Comment by ANSHUMAN87** [comment]
@tqchen : If no further concern here! Would you please help to get this PR merged with latest docker images. So that our forth coming Sparse PRs will be smooth to handle. TIA!

**Review by tqchen — APPROVED** [review]

**Comment by tqchen** [comment]
FYI https://github.com/apache/incubator-tvm/issues/6754

**Comment by ANSHUMAN87** [comment]
> FYI, we will need to resolve #6754 in order to upgrade the TF images to 2.3.1

Thanks @tqchen, I will look into it.

**Comment by leandron** [comment]
We are facing issues (reported broken TFlite tests #6754) when using the latest Docker files to run tests in our downstream CI.

Can we temporarily revert this change here, so that it is merged again when the rest of the sources are prepared to support TF 2.3.x?

**Comment by tqchen** [comment]
@leandron  feel free to send a PR to revert the version

**Comment by ANSHUMAN87** [comment]
> We are facing issues (reported broken TFlite tests #6754) when using the latest Docker files to run tests in our downstream CI.
> 
> Can we temporarily revert this change here, so that it is merged again when the rest of the sources are prepared to support TF 2.3.x?
> 
> cc @u99127

I am working on the fix currently. Thanks!

**Pull request merged**
