### PR TITLE
[PYTORCH]Reduce_ops support added

### PR DESCRIPTION
**Pull request by siju-samuel**
- Fixed reduce_sum
- Fixed reduce_prod
- argmin
- argmax
- std
- variance
@masahi please help to review and merge this PR.  Thanks in advance.

### CODE REVIEW

**Comment by masahi** [comment]
@siju-samuel please fix the CI error

**Comment by masahi** [comment]
"Test code" doesn't mean code quality can be low. Add blank lines following established python style convention. Each functions are supposed to have two blank lines between them

**Comment by siju-samuel** [comment]
@masahi Thanks a lot for the review. Updated.

**Comment by masahi** [comment]
@siju-samuel sorry my PR https://github.com/apache/incubator-tvm/pull/5306 was just merged and has conflict with this one. Can you rebase?

**Comment by masahi** [comment]
@siju-samuel sorry again, I just found a typo bug in our qnn test https://github.com/apache/incubator-tvm/blob/03cbf78e3e8cc910c5a9c95cd3fcafa19959644f/tests/python/frontend/pytorch/qnn_test.py#L399

Can you change `pt_result` there to `tvm_result`?

**Comment by siju-samuel** [comment]
thanks @masahi, Done. Please have a look

**Comment by masahi** [comment]
Thanks!

**Pull request merged**
