### PR TITLE
[CRT]fix to reduce RAM size during loading model

### PR DESCRIPTION
**Pull request by siju-samuel**
Free the graph_json immediately after loading the graph to runtime. This will help in saving some RAM for low memory devices.

@liangfu @tmoreau89 Please help to review this code.

### CODE REVIEW

**Comment by siju-samuel** [comment]
@tqchen could you please review. Thanks.

**Comment by tqchen** [comment]
I am a bit confused by why the bits field is necessary, would it suffice to just check the dtype of each tensor and compute the maximum size correctly?

**Comment by tqchen** [comment]
@siju-samuel do you mind elaborate? I still do not see why do we need to specify bits here. Is it because your pool contains a lot of single element data? Since it is totally fine to allocate array using float32 and recast to int8, as long as these arrays have at least 4 elements.

**Comment by siju-samuel** [comment]
@tqchen I work in a device with very limited ram availability. Actually even a few kbs is crucial for me.

Im using a quantized model and the pool is 80% unit8 data. So i dont want to allocate all pool with float and 32bit. If i consider the bit i can restrict all pool to allocate 32bit.

So while allocating space, to compute `size` we either need `bits` or `dytpe`. Now both are not available in `TVMGraphRuntimePoolEntry`. So i added bits in `TVMGraphRuntimePoolEntry`

As you suggested, we can compute `size` while finding maximum space needed and save to  `pool_entry[sid].size` 
But it requires either 
1. while making TVMNDArray_Empty, always use `dtype.code = kDLInt` & `dtype.bits = 8`.

2. while making TVMNDArray_Empty, use Float & 32bit (like before this change) and reduce the `size` as per `bits` and align to 4bytes.

I would like to go with 2nd approach. I havnet done the modification yet. I will do the modifications, test and will update this PR.

**Comment by tqchen** [comment]
shouldn't the `size` argument in the pool already is reflected number of bytes(thus taking the data type into consideration?)

**Comment by siju-samuel** [comment]
@tqchen Ideally yes. There may be some calcuation issue. I will verify once again in case of crt what is happening and get back.

**Comment by siju-samuel** [comment]
@tqchen Thanks a lot. The 40kb ram reduced for me was due to the free of graph_json I freed immediately after saving to runtime. 
The other fix on setupstorage could save me only around 200bytes totally, which is not very significant. Sorry that I overlooked the other change.

**Pull request merged**
