### PR TITLE
[ROCM] Support rocblas_sgemm_strided_batched

### PR DESCRIPTION
**Pull request by csullivan**
Support rocBLAS batched GEMM and prioritize rocBLAS strategy over codegen when no costs are provided via a tuning config. Also canonicalize invocation of column major rocBLAS APIs for matmul and batched_matmul.

### CODE REVIEW

**Comment by csullivan** [comment]
cc @masahi

**Comment by masahi** [comment]
please take a look at the CI problem

**Review by masahi — APPROVED** [review]

**Comment by masahi** [comment]
thanks @csullivan

**Comment by csullivan** [comment]
Thank you @masahi !

**Pull request merged**
