### PR TITLE
Update install.rst

### PR DESCRIPTION
**Pull request by badenh**
minor cleanups/corrections

Thanks for contributing to TVM!   Please refer to guideline https://tvm.apache.org/docs/contribute/ for useful information and tips. After the pull request is submitted, please request code reviews from [Reviewers](https://github.com/apache/incubator-tvm/blob/master/CONTRIBUTORS.md#reviewers) by @ them in the pull request thread.

### CODE REVIEW

**Comment by tmoreau89** [comment]
Looks like one of the edits on the section titles is breaking a link in the RST. Can you fix line 23 of the file to add the missing "VTA "? Thanks

**Comment by tmoreau89** [comment]
Until then we cannot merge the fixes.

**Comment by tmoreau89** [comment]
@badenh Please let us know if you can fix the install.rst to pass the CI tests

**Comment by badenh** [comment]
Yes, fixed the missing item now

**Comment by tmoreau89** [comment]
thank you @badenh your changes have been merged

**Pull request merged**
