### PR TITLE
Fix serialization of inf float value

### PR DESCRIPTION
**Pull request by lixiaoquan**
@tqchen Could you please take a look?

### CODE REVIEW

**Comment by tqchen** [comment]
Thanks @lixiaoquan ! it appears that I merged pre-maturely, can you followup with a testcase that covers the fix? Thank you

**Comment by junrushao1994** [comment]
Good catch! Do we also want to support NaN as well?

**Comment by lixiaoquan** [comment]
> Thanks @lixiaoquan ! it appears that I merged pre-maturely, can you followup with a testcase that covers the fix? Thank you

This PR includes a test called test_infinity_value().

**Comment by lixiaoquan** [comment]
> Good catch! Do we also want to support NaN as well?

Thanks for mentioning that, I'll send another PR for that

**Pull request merged**
